### ISSUE TITLE
Reliable Email Delivery

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#10]
As a user, I want to reliably receive emails, so I can access training, generate reporting (as permitted), and retrieve certificates.

Currently, the program uses a private email server and the email address used is not an actual .gov address.  This means that agencies can tend to filter out emails from our system. For some agencies, this is intermittent.  However, there are some agencies that filter out most, if not all emails generated from our training site because of this.  Having a government controlled and verified .gov address may help mitigate some of these issues.

Acceptance criteria:
- Email servers used are government owned and operated [Solutioning? What SmartPay really wants to ensure is that emails are reliably sent and received. What are other govt entities doing to ensure email delivery?]
- Emails to users are sent from smartpay-noreply@gsa.gov

Potential post-MVP (unless this is OOTB):
- GSA SmartPay can determine when a user opens the email
- GSA SmartPay can monitor bounce backs

**Comment by JessicaMarine1** [comment]
@A-L33 to provide more background / context

**Comment by jfredrickson5** [comment]
Do we have any contacts at agencies that are known to filter SmartPay emails? It would be nice to verify with them if our solution is working.

**Comment by johnbeallgsa** [comment]
John will find an agency that currently can't receive SmartPay emails.

**Comment by johnbeallgsa** [comment]
I see the the most emails from  the United States Department of the Treasury about needing the password reset.  I can reach out to them if you need me.  

I will keep looking for additional agencies.

**Comment by JessicaMarine1** [comment]
@A-L33 please provide some specific emails that @jfredrickson5 can send test emails to.

**Comment by A-L33** [comment]
Reaching out to DoD Purchase, Treasury, and USPS.  When final, the list will be **[HERE](https://docs.google.com/spreadsheets/d/1fhsn_ENiYC-4iy-ccXKAwHg7YqhWiLjBGtszpmaTjag/edit#gid=1911795550)**, under the "Email List" tab.  Please standby.

**Comment by A-L33** [comment]
Draft emails for review.  Note, DoD Purchase had specific instructions.  Once we finalize on our side, I'd like to give it back to the A/OPC for review.

**DoD Purchase**
Dear DoD purchase card stakeholder,

The GSA Center for Charge Card Management manages the GSA SmartPay training website (https://training.smartpay.gsa.gov).  The program is in the process of improving email functionality and reliability -- such as password reset emails -- and you are receiving this email because you have contacted our customer service help desk (gsa_smartpay@gsa.gov) within the last 2 years for assistance.

Please confirm that you have received this email, please click on the link here:  xxxxxxx.gov.

As a reminder, the Defense Purchase Card (DPC) program continues to track users’ training completion in PIEE/EDA (and not in GSA’s training tracking tool).  Please continue to track your training compliance through PIEE/EDA.

For questions about the authenticity of this email, please reach out to the GSA SmartPay customer service inbox at gsa_smartpay@gsa.gov.

Thank you,


**USPS**
Dear USPS charge card stakeholder,

The GSA Center for Charge Card Management manages the GSA SmartPay training website (https://training.smartpay.gsa.gov).  The program is in the process of improving email functionality and reliability -- such as password reset emails -- and you are receiving this email because you have contacted our customer service help desk (gsa_smartpay@gsa.gov) within the last 2 years for assistance.

Please confirm that you have received this email, please click on the link here:  xxxxxxx.gov.

For questions about the authenticity of this email, please reach out to the GSA SmartPay customer service inbox at gsa_smartpay@gsa.gov.

Thank you,

**Comment by JessicaMarine1** [comment]
5/23/2023 - Jessica sent the following email to 11 individuals at USPS:

Dear USPS charge card stakeholder,

The GSA Center for Charge Card Management manages the GSA SmartPay training website (https://training.smartpay.gsa.gov/). The program is in the process of improving email functionality and reliability -- such as password reset emails -- and you are receiving this email because you have contacted our customer service help desk ([gsa_smartpay@gsa.gov](mailto:gsa_smartpay@gsa.gov)) within the last 2 years for assistance.

In order to confirm that you can successfully receive emails from the new system, we ask you to:

1. Visit the new quiz [registration page](https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/test/quiz/training_travel/)

2. Enter your email, name & agency

3. Click `Submit`

4. Respond to **THIS** email to confirm whether you received an email from GSA SmartPay Training ([smartpay-noreply@gsa.gov](mailto:smartpay-noreply@gsa.gov)) at the email address you provided.

Please let me know if you have any questions.

Thank you,

**Comment by A-L33** [comment]
@JessicaMarine1 Revisions from DoD Purchase, please use the version below!

Dear DoD purchase card stakeholder,

The GSA Center for Charge Card Management manages the GSA SmartPay training website ([https://training.smartpay.gsa.gov/](https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Ftraining.smartpay.gsa.gov%2F&data=05%7C01%7Csheila.a.mcglynn.civ%40mail.mil%7C21c6acf8c8b147191ee008db5c5ac533%7C102d0191eeae4761b1cb1a83e86ef445%7C0%7C0%7C638205317160582663%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UVPqlMcKvwULm8bC7cfSlkXXTOGAP1Y8A9P04evTGw4%3D&reserved=0)). The program is in the process of improving email functionality and reliability -- such as password reset emails -- and you are receiving this email because you have contacted our customer service help desk ([gsa_smartpay@gsa.gov](mailto:gsa_smartpay@gsa.gov)) within the last 2 years for assistance.

In order to confirm that you can successfully receive emails from the new system, we ask you to:

1.       Visit the new quiz [registration page](https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Ffederalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov%2Fpreview%2Fgsa%2Fsmartpay-training%2Ftest%2Fquiz%2Ftraining_travel%2F&data=05%7C01%7Csheila.a.mcglynn.civ%40mail.mil%7C21c6acf8c8b147191ee008db5c5ac533%7C102d0191eeae4761b1cb1a83e86ef445%7C0%7C0%7C638205317160582663%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Pl3%2FkKzt7C0PSv21Yzn5YNqzYut%2FGvy9Ucwlr1%2Bc6%2Fw%3D&reserved=0)

2.       Enter your email, name & agency

3.       Click Submit

4.       Respond to THIS email to confirm whether you received an email from GSA SmartPay Training ([smartpay-noreply@gsa.gov](mailto:smartpay-noreply@gsa.gov)) at the email address you provided.

Please let me know if you have any questions.

**As a reminder, the Defense Purchase Card (DPC) program links to its DoD GPC Program’s required and recommended training at [ASD(A) - DPC - Contracting eBusiness (osd.mil)](https://www.acq.osd.mil/asda/dpc/ce/pc/training.html), and continues to track users’ training completion in PIEE (and not in GSA’s training tracking tool). Please continue to track your training compliance through PIEE.  For further information, see One Pager 30P038, Tracking Training in PIEE, at the aforementioned training link.**

Thank you,

**Comment by JessicaMarine1** [comment]
5/24/2023: sent emails to DoD participants
5/25/2023: sent email to Sean (Treasury) with instructions; asked him to have some folks test the flow

**Comment by JessicaMarine1** [comment]
@A-L33 we've received confirmation from USPS & Treasury, but no one from DoD. Next week, can you send the instructions to the DoD A/OPCs and have them test?

**Comment by A-L33** [comment]
@JessicaMarine1 Emailed DoD to ask management to help out.  A contractor responded positively but will need .gov and .mil emails to test.

**Comment by JessicaMarine1** [comment]
5/30/2023 update:
We've received confirmation from USPS and Treasury (and related orgs) that our emails are coming through just fine. For DoD, the emails are coming through but being routed to SPAM. A couple of things to consider:

- Work with them to get smartpay-noreply@gsa.gov email address “white-listed”, if possible
- Add language to the confirmation screen about “checking SPAM folder”

**Comment by JessicaMarine1** [comment]
@A-L33 I know there is some additional discussions needed with DoD, but the development work for this is _probably_ done for now. If you agree, I think this can be called `DONE`

**Comment by A-L33** [comment]
@JessicaMarine1 Agreed.  Let's chat about this next week because I've not gotten very far with DoD.  If we need to make any changes on our side, we can write a new story.

**Comment by A-L33** [comment]
Done!  Note that I ran into bug #207 a couple times with past certs but it seems to be working for quizzes.
