### ISSUE TITLE
Authorized User Language

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#105]
As an administrator, I want to make sure that individuals coming to the site understand that it has a specific purpose and to help prevent unauthorized users from abusing the training system.

Acceptance Criteria:
- Upon display of user email field, display the following message in an alert box:
  - "This is a U.S. Federal Government system. Use of this system and issued certificates is for federal employees, tribal government organizations, and other authorized users only."

Design in comments based on https://designsystem.digital.gov/components/alert/
Figma: https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?node-id=851-13958&t=yLEZY9KftiwHbRUu-4

Test cases:
- [ ] Kicking off quiz registration
- [ ] Kicking off "Access Past Certificates" flow

**Comment by JessicaMarine1** [comment]
Do we need the word "system" twice? Could you delete the first one? Also should United States be U.S. instead? Suggested re-wording: 

"This is a U.S. Federal Government system. Use of this system and issued certificates is for federal employees, tribal government organizations, and other authorized users only."

**Comment by melchoyce** [comment]
How's something like this? 
![image](https://user-images.githubusercontent.com/2846578/234674202-89b668f5-4ffe-4322-a145-b7f7a01cd076.png)

**Comment by A-L33** [comment]
I'm good with this!

**Comment by melchoyce** [comment]
Great, updated in Figma: https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?node-id=851-13958&t=yLEZY9KftiwHbRUu-4

**Comment by A-L33** [comment]
Done!

**Comment by A-L33** [comment]
For sprint review - This was a user story based on Dave's feedback from sprint review for Sprint 5.
