### ISSUE TITLE
Content edits (part 2) | Travel Training for Card/Account Holders and Approving Officials

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#108]
- [ ] Please update the content of the Travel Training for Card/Account Holders and Approving Officials as indicated by suggested edits [here](https://docs.google.com/document/d/13GupbzWON7SJOWdXHmvOxsdvnQohQXHIzuPJU61fdJk/edit#heading=h.nax8fy957bvn).
- [ ] Please update the last item (the quiz) on the left nav to say `QUIZ: GSA SmartPay Travel Training (Card/Account Holders and Approving Officials)`

**Comment by weiwang-gsa** [comment]
@A-L33 Just to confirm following:

1.below is just change "the" to "a", and "account" to "card", not "card/account"

![Image](https://user-images.githubusercontent.com/119954777/234907762-48725e84-1457-4cd8-98ac-6ed6ae72afc2.png)

2.assumed "an" will be changed to "a"


![Image](https://user-images.githubusercontent.com/119954777/234908042-7d6fcb66-51e8-477f-8ff6-58254a80f362.png)

**Comment by A-L33** [comment]
@weiwang-gsa Confirmed!  The accountholder is being sent a physical card, so just card here.  Thank you!

**Comment by A-L33** [comment]
@weiwang-gsa Good catch, the correction was a mistake.  This should have remained Individually Billed Accounts (IBA).  Shouldn't have the card/account there.  Thank you!

**Comment by weiwang-gsa** [comment]
@A-L33 Thanks for confirmation, then can I safely assume CBAs and Tax Advantage Travel Accounts also should not be changed? 

![Image](https://user-images.githubusercontent.com/119954777/234918812-b4c2b74b-d174-4a99-ba5e-af47584a26de.png)

**Comment by A-L33** [comment]
Yes, confirmed.  Thank you!

**Comment by weiwang-gsa** [comment]
@A-L33, sorry couple of new questions, I put in comment in the document and tag you there directly there. Thank you!

**Comment by A-L33** [comment]
@weiwang-gsa Thank you Wei, I just went through the document and did another look through.  Should be clean now.

**Comment by weiwang-gsa** [comment]
@A-L33 I am double checking the whole document again, and here is the last question:

Should we change this "account" to "card/account"?

![Image](https://user-images.githubusercontent.com/119954777/235466443-fb8e27c2-b073-4fa6-b810-645efdfab398.png)

**Comment by A-L33** [comment]
@weiwang-gsa Yeah, let's change that to card/account.

**Comment by A-L33** [comment]
Done!
