### ISSUE TITLE
Content edits | Travel Card Training for Account Holders/AOs

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#109]
For the Travel Card Training for Account Holders/AOs, please incorporate the following content edits:

- [ ] Remove the (R) mark from all incidents of SmartPay throughout the training **except for** the first one
- [ ] Search for Smart**p**ay to ensure the P is capitalized
- [ ] Change each instance of `account holder` to `card/account holder`

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 , does the first one refer to below screen shot?  Just double check if we should keep this one's (R)


![Image](https://user-images.githubusercontent.com/119954777/231569028-22b91527-80e7-4896-aa03-f7f8abd68c4b.png)

**Comment by JessicaMarine1** [comment]
@weiwang-gsa Actually I think it needs to be added to the Introduction page and removed from Lesson 1 ^^^
![Screen Shot 2023-04-12 at 3 55 21 PM](https://user-images.githubusercontent.com/92383362/231570316-9e568992-6e2e-4a8c-aa98-7d1068efb2f0.png)

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 Thanks for clarification. I will add R to introduction and move it from lesson 1.

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 just double check it is card/account holder, no space between /, not "card / account holder", right? I searched wiki, seems suggestion is to remove space between/ unless it is poem. But I saw there are space between / on home page, so just want to double check with you, if no space, I will remove space on home page as well.

**Comment by JessicaMarine1** [comment]
@brentryanjohnson suggests removing the spaces.

**Comment by JessicaMarine1** [comment]
@weiwang-gsa Anywhere that `account holder` appears (regardless of case), please change to `card/account holder`. So yes to 1, 2 & 4.

I am going to work with Andrew to develop a list of where we need to change `account` to `card/account` because that change is _not_ universal. So, no to 3 for now.

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 @A-L33  @johnbeallgsa This is ready for QA: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/

**Comment by A-L33** [comment]
@johnbeallgsa If you are working tomorrow, could you QA this?  If not, I can get to it on Tuesday.  Just let me know!

**Comment by johnbeallgsa** [comment]
@A-L33 - I have a question about using GSA SmartPay - according to our style guide - The program should be referred to as the “GSA SmartPay program.” “GSA” must always come before “SmartPay.”  This might be out of scope or a parking lot issue.  Let's discuss on Monday.

**Comment by JessicaMarine1** [comment]
@johnbeallgsa I too have found a few places where we don't have the GSA before SmartPay. I've added another issue to make sure we check this everywhere on the site before launch. Because this is out of scope for this issue, if everything else that was intended to be fixed has been, we should move it to done.

**Comment by johnbeallgsa** [comment]
Moving to done.  This looks great @weiwang-gsa

**Comment by A-L33** [comment]
@weiwang-gsa @johnbeallgsa Apologies, I found one quick edit.  Please uncapitalize the "program" from the first title here:  https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/training_travel/lesson01/.

**Comment by JessicaMarine1** [comment]
Moved this capitalization issue to #116; moving card to `Done`
