### ISSUE TITLE
Training | Purchase Card Training for Card/Account Holders & Approving Officials

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#11]
As a user of the site, I want to access Purchase Card Training for Card/Account Holders & Authorizing Officials without registering (providing an email), so I can view/print training materials.

**Pre-Condition:**
Training material content is complete [HERE](https://docs.google.com/document/d/1nPkZ0KSn8uyBfFUl_HhXcSG8zaaePsg2kamWL1hJq3Q/edit).

**Acceptance criteria:**
- [ ] Users can progress through each lesson of the training in the browser without providing an email address
   - Note: this should have the same exact look / experience as the [Travel Card Training for Card/Account Holders & Certifying Officials](https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/training_travel/)
- [ ] Users can access quiz registration form from end of training material
- [ ] Users can view & print a 508 compliant, print-friendly version of the full training

**Comment by A-L33** [comment]
@brentryanjohnson Please review content!

**Comment by brentryanjohnson** [comment]
@A-L33 ✅ Reviewed

**Comment by A-L33** [comment]
Content good to go!

**Comment by A-L33** [comment]
Done!
