### ISSUE TITLE
Content edits | Travel Training Quiz (Account Holders/AOs)

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#110]
For the Travel Training Quiz for Account Holders/AOs, please incorporate the following content edits:

- [ ] Remove the period from the end of each answer option
- [ ] Remove the (R) mark from all incidents of SmartPay throughout the quiz **except for** the first one (Question 2 -- needs to be added)
- [ ] Search for Smart**p**ay to ensure the P is capitalized
- [ ] Change each instance of `account holder` to `card/account holder`

Note: Please do not change `account` to `card/account` in places where it is not currently `account holder`. We need to determine those changes on a case-by-case basis.

**Comment by A-L33** [comment]
@jfredrickson5 
- For answer "I am not responsible for making payment. My agency is responsible" on question 6, please change to:  "I am not responsible for making payment; my agency is responsible" here:  https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/quiz/training_travel/
- Please change "account" to "card" in question 14 here:  https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/quiz/training_travel/

**Comment by A-L33** [comment]
@jfredrickson5 Please hold off until I chat with Jessica.  Thank you!

**Comment by JessicaMarine1** [comment]
@A-L33 @johnbeallgsa This is ready for your re-review.

**Comment by A-L33** [comment]
Done!
