### ISSUE TITLE
📋 Reflection | Email Server

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#114]
Getting a working email server for the SmartPay project turned out to be much harder than expected. In the spirit of our third [prong](https://docs.google.com/presentation/d/1rge75lf4L2WjQv-2NF3KhdayCqhvj6puI8mpZnKwupk/edit#slide=id.g18f5134ca85_1_0) let's:
- [ ] Put together a [timeline](https://docs.google.com/document/d/1RndXk2Cc_nAy9wxFnx0KePUyx3jPQmeWAfOJ2F8rhZU/edit#) (date, who, what happened) on the email server thing
- [ ] Suggest GSAIT do some blameless [reflection](https://docs.google.com/document/d/1V5NnLcxsBwuOq3Dub6DI6WDPuvOZ8s0cqXMu5YM6Gxs/edit) on it

**Comment by vickimcfadden** [comment]
February 6 - Mark Meyer - opened help desk ticket requesting SMTP server access (RITM1049649)
March 16 - Mark Meyer - emailed Chris McFerren and Amar Singh to give more context on the help desk ticket
March 20 - David Shive - escalated blocker to CIO and he suggested we escalate to GSAIT leadership
March 21 - Liz DelNegro - escalated blocker to Associate CIO
March 21 - Chris McFerren - emailed us that Ted Kruelski would be able to help
March 21 - Matt McGuire - emailed us that Mannish and Narendra would be able to help
