### ISSUE TITLE
Training Material Mobile Access

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#12]
As a general user, I want to access the training platform from my mobile device, so I can review training modules without using a laptop.

Acceptance criteria:
- User is able to access all the training material from a mobile device
- User is able to download/print the full training from a mobile device
  - Note: this story is intended to capture design tweaks, if any, that might be needed for the training flow on mobile
- See design changes in comments below

**Comment by JessicaMarine1** [comment]
Does user need to be able to download / print from mobile? Is the intent to have the same functionality as if on the desk/laptop?

**Comment by JessicaMarine1** [comment]
@melchoyce for this story, please test the training functionality (including downloading/printing full training) on mobile and see if you have any design changes.

**Comment by melchoyce** [comment]
This is looking great!

I have a few global items that I think we should update:

# Primary navigation

The "menu" button doesn't have `cursor: pointer` on it. We should include the cursor change for people using smaller browser windows or with small desktop screens.

# Page header

## Before
Spacing between the subtitle and page title is tight.
![image](https://user-images.githubusercontent.com/2846578/234419847-104c3fda-1553-44f8-a556-07f30557ffd7.png)

## After
.5em of spacing:
![image](https://user-images.githubusercontent.com/2846578/234419633-004331d8-dd59-46ce-81a3-d42b0b082bbb.png)

# Contact footer

## Before
Text goes up to the divider line in the middle of the container
![image](https://user-images.githubusercontent.com/2846578/234418246-941dc11c-1e90-409d-88df-5d90feef39f3.png)

## After
Left column has 2ems of padding on the right
![image](https://user-images.githubusercontent.com/2846578/234418390-fc26242e-da33-469f-a355-4b631efa1d36.png)

Let's also use the default link color (#005ea2) for the links in this container.
![image](https://user-images.githubusercontent.com/2846578/234418946-ebde88b6-5b7b-4725-adde-05121604ada9.png)

# Global footer

## Before
Spacing doesn't match the 2ems of the contact footer
![image](https://user-images.githubusercontent.com/2846578/234419131-f17022a6-d731-4ab8-9c0a-ce800faa3bc1.png)

## After
Footer has 2ems of padding inside it
![Screen Shot 2023-04-25 at 6 36 39 PM](https://user-images.githubusercontent.com/2846578/234419072-481cfc49-9c03-4ce3-83ec-8251cbfbf651.png)

(This should be updated across all screen sizes)

# Page content

This isn't specific to mobile, but can we remove the border on the asides?

## Before
![image](https://user-images.githubusercontent.com/2846578/234421246-0544c73b-673a-4c79-98ea-2458de98f77f.png)

## After
![image](https://user-images.githubusercontent.com/2846578/234421135-3a923619-0fdb-45fa-9c34-49348e6ac789.png)

Or, if we're concerned about contrast, reduce the border opacity to 25%:

![image](https://user-images.githubusercontent.com/2846578/234422330-1e37beeb-c6c0-42fe-8db7-31954bacec20.png)

**Comment by A-L33** [comment]
@melchoyce Please check the downloaded training doc.

**Comment by JessicaMarine1** [comment]
@melchoyce @A-L33 I tried the view/print full training flow on mobile and it loads just fine but when I click the "Print Training" button, the print layout is kinda weird -- the pages are breaking differently than on desktop.


![Image](https://user-images.githubusercontent.com/92383362/234863433-304cd52a-c9c7-4388-b41e-3542d9a9adfc.jpg)


Is this something we can live with or do we need to fix it?

**Comment by A-L33** [comment]
Agreed, if this is fixable, that's great.

**Comment by melchoyce** [comment]
Would be great to fix this if we can—hopefully just a few lines of print stylesheet fixes?

**Comment by weiwang-gsa** [comment]
@melchoyce @A-L33  This is ready for QA : https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/

@melchoyce Just let you know I've added cursor pointer to menu button, but I did not notice there is any change on mobile view though, and I checked USWDS in mobile view, it the same behavior, it just render a circle dot for indication.

**Comment by melchoyce** [comment]
Great, will test this out!

> Just let you know I've added cursor pointer to menu button, but I did not notice there is any change on mobile view though, and I checked USWDS in mobile view, it the same behavior, it just render a circle dot for indication.

That's expected, the cursor is a desktop enhancement 👍  Thanks for noting!

**Comment by melchoyce** [comment]
Sidebar change works great! Tested on my phone and on desktop.

I only have one minor update—can you increase the spacing from `margin-bottom-2` to `margin-bottom-4` between the select and the heading underneath it?

![image](https://user-images.githubusercontent.com/2846578/236255367-0ef7df95-0693-4812-b692-e234cee243ff.png)

Will test the other updates next!

**Comment by melchoyce** [comment]
Can we make some more updates to that pre-footer container so it lines up with the content above and the footer below?

![Group 536](https://user-images.githubusercontent.com/2846578/236268602-14926ef5-454b-48dc-b58f-d9afa3c19c13.png)

Everything else looks good to me 👍

**Comment by A-L33** [comment]
@weiwang-gsa Pulled this back out to in progress.

**Comment by weiwang-gsa** [comment]
@melchoyce it is ready for QA: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/training_travel/

Please note  I have to make the spacing as 2em on the right hand side, and 0em on the left hand side for Desktop view due to the email address wrapped to 2nd line on desktop view, and made 1em for both side for mobile view. If I keep all 1em, the desktop will looks uneven do to email address wrapping.

**Comment by melchoyce** [comment]
Looks like there's still some additional padding coming from another container on mobile:

![image](https://user-images.githubusercontent.com/2846578/236298412-61976f6f-d36c-48b8-8861-f01ca3ec2623.png)

Are we able to get rid of that?

**Comment by melchoyce** [comment]
Update: we troubleshooted and it seems to be maybe my desktop cache not clearing or something, it looks correct on my phone.

**Comment by weiwang-gsa** [comment]
@A-L33 it passed Mel's review, please QA: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/training_travel/

**Comment by A-L33** [comment]
Done!
