### ISSUE TITLE
Content edits (part 2) | Card/Account Holders and Approving Officials Travel Training Quiz

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#127]
Please update the content/design of the Card/Account Holders and Approving Officials Travel Training Quiz as indicated by suggested edits [here](https://docs.google.com/document/d/19RS0F0yeNvi3t4XDPegKikmQnBx_PotcJv9nRoI4cCM/edit#).

**Comment by JessicaMarine1** [comment]
Moved acknowledgment statement changes to #150.

**Comment by A-L33** [comment]
Done!
