### ISSUE TITLE
Content edits (part 2) | A/OPC Travel Training Quiz

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#128]
Please update the content/design of the A/OPC Travel Training Quiz as indicated by suggested edits [here](https://docs.google.com/document/d/1A9QZK4kGnTApDuu0VnnZYNOo_w_Qxb7cX6WwLLTYnKw/edit#heading=h.gjdgxs).

**Comment by JessicaMarine1** [comment]
Moved acknowledgement statement changes to #150.

**Comment by A-L33** [comment]
Done!
