### ISSUE TITLE
Front-end accessibility checks

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#131]
Moved from #63: 
Accessibility checks on the front-end may require more work that typical static sites. I think this warrants pulling it out as it's own ticket. The way we typically do accessibility scans is to build the website, then crawl each page and pass it through the scanner. This will work on the static parts of this site (the training material), but won't work for the parts that are behind the loginless wall. These are the more difficult parts to get right in terms of accessibility. We may be able to scan these in the linting / unit-test scans, but this will require a spike to figure out how to do it.

**Acceptance Criteria:**

- [x] Implement front-end accessibility checks

**Comment by mark-meyer** [comment]
This one is a little hard to QA. We did the following:

1. Added linting rules (these are rules the look at the code and test whether it conforms to certain standards). We added rules to check the individual components against standard accessibility guidelines. 
2. Add pa11y checks to the ci-cd pipeline. These build the pages and then use a browser-like tool to check the pages at both desktop and mobile sizes. You can see these run with pull-requests in github. The attached screen shot is what it looks like.
3. Made a handful of changes based on the above tests to make them all pass.



![Image](https://user-images.githubusercontent.com/7340303/235710232-c10a771d-a12a-428e-993f-d99c8cdb2174.png)

**Comment by A-L33** [comment]
Thanks @mark-meyer.  Done!
