### ISSUE TITLE
Implement DAP Analytics

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#132]
As the GSA SmartPay program, I need access to analytics from the training site, to help report to management and make future decisions.

**Acceptance Criteria:**

- [ ] Add DAP analytics to the SmartPay training site
- [ ] ~~Ensure SmartPay POs have access to and know how to pull DAP analytics~~ [moved to #158]

**Comment by A-L33** [comment]
@A-L33 Figure out DAP.

**Comment by JessicaMarine1** [comment]
@A-L33 I think we figured this out. It looks like it's the same snippet for all websites. https://github.com/digital-analytics-program/gov-wide-code/blob/master/documentation/GSA%20DAP%204.1%20-%20Quick%20Guide.pdf

**Comment by mark-meyer** [comment]
This has been added to the pages. We just need to figure out how to ensure POs have access.

**Comment by A-L33** [comment]
Looks like SmartPay has a Google Analytics account.  I have the login and password.  Let me know if this what I needed to find.

**Comment by JessicaMarine1** [comment]
I'm going to pull the second AC--PO has access and knows how to access analytics--into another story, bc until this site goes live it will be hard to satisfy it.

**Comment by mark-meyer** [comment]
It's a little hard to demonstrate that this is setup. But we can show that the page is loading the analytics code from dap and google-analytics:



![Image](https://user-images.githubusercontent.com/7340303/235022354-59b592c7-69b2-46df-bea5-5c3f5464e550.png)

**Comment by A-L33** [comment]
Thank you!  Done!
