### ISSUE TITLE
Usability Testing | Training-->Quiz-->Certificate flow

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#148]
Now that we have the full training-->quiz-->certificate flow done, we'd like to get some feedback from users.

**Acceptance Criteria:**

- [x] Step up [truncated training/quiz](https://github.com/GSA/smartpay-training/issues/148#issuecomment-1527556656) on a separate branch
- [x] Recruit users (Vicki volunteered to lead effort)
- [x] Develop testing [script](https://docs.google.com/document/d/1wasZgg1fEdMn6Z0tLwc1X9lVHuH9Bs_QhowzobYTkRo/edit#heading=h.9ut05kq1320r)
- [x] Conduct usability testing
- [x] Present [findings/recommendations](https://docs.google.com/presentation/d/1CXmW0nJq9ehc03xjpmXbpzjazEJwCPFXACDK6zslrto/edit#slide=id.g2371cf644b0_0_475) to PO
- [x] Backlog changes (MVP v. post-MVP)

**Comment by A-L33** [comment]
@A-L33 Find users.

**Comment by A-L33** [comment]
Truncated version = 2 training pages and 3 quiz questions.

**Comment by JessicaMarine1** [comment]
@mark-meyer @weiwang-gsa @jfredrickson5 For the truncated versions, let's do: 

**Training**
- Welcome page of Travel Training for Card/Account Holders & Approving Officials
- Current Lessons 1 & 9
- Rename ^^^ to lessons 1 & 2 please

**Quiz**
- Questions 1, 5, 6, 8 & 9 of current Card/Account Holders and Approving Officials Travel Training Quiz
- Renumber ^^^ to questions 1-5 please

**Comment by vickimcfadden** [comment]
[Usability testing script](https://docs.google.com/document/d/1wasZgg1fEdMn6Z0tLwc1X9lVHuH9Bs_QhowzobYTkRo/edit#heading=h.9ut05kq1320r)

**Comment by vickimcfadden** [comment]
Given I'm out next week, realistically, we most likely won't be able to complete this in the current sprint.

**Comment by mark-meyer** [comment]
The truncated quiz is ready to be uploaded to the test back-end when it is deployed: https://drive.google.com/drive/folders/1iV7cvhvfuFEMOHH3J-b_8rH7QeQK280A

**Comment by JessicaMarine1** [comment]
@A-L33 yes, we only set up one training --> quiz flow for testing.

@mark-meyer this looks great!

@vickimcfadden @melchoyce I added the URL to the testing script.

**Comment by mark-meyer** [comment]
@A-L33 Yes, I think they are going to focus on travel card holder training. Now that it's setup, it shouldn't be difficult to make changes should we need them.

**Comment by vickimcfadden** [comment]
@A-L33 gave us a huge list of users to pull from that have contacted the SmartPay help desk regarding training issues over the last 2 years! https://docs.google.com/spreadsheets/d/1fhsn_ENiYC-4iy-ccXKAwHg7YqhWiLjBGtszpmaTjag/edit#gid=825012245

I'll start contacting folks to set-up usability testing tomorrow morning!

**Comment by A-L33** [comment]
@vickimcfadden Chatted with @@melchoyce and @brentryanjohnson today.  I offered the list to them too should they need to do any tree testing or usability testing for the website,  Let me know if you have any concerns.

**Comment by vickimcfadden** [comment]
Wahoo no concerns!

**Comment by vickimcfadden** [comment]
I reached out to 8 users from the list Andrew provided today.

**Comment by vickimcfadden** [comment]
@A-L33 @JessicaMarine1 cc: @klohman 

[Usability results](https://docs.google.com/presentation/d/1CXmW0nJq9ehc03xjpmXbpzjazEJwCPFXACDK6zslrto/edit#slide=id.g2371cf644b0_0_475). When y'all feel comfortable that the issues are captured in the backlog, I think we can close this ticket.
