### ISSUE TITLE
SmartPay's Cloud.gov Pages

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#149]
Set up SmartPay's Cloud.gov Pages account.

**Acceptance Criteria:**
- Each engineer has access to Pages account
- Set up a site in Pages that is connected to the GitHub repository.

**Comment by A-L33** [comment]
@jfredrickson5 I added the entire team to the Cloud.gov Pages account.  Let me know if you have any access issues.

**Comment by jfredrickson5** [comment]
@A-L33 Looks perfect, thanks!

**Comment by A-L33** [comment]
Done!
