### ISSUE TITLE
Quiz Acknowledgment Statements

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#150]
Currently, the quiz acknowledgment statements are a re-usable component. The program would like each acknowledgment to reference the type of training and type of user [bolded below]:

Travel Training for Agency/Organization Program Coordinators (A/OPCs): 
☑ “I acknowledge that I’ve read and understand the policies and regulations that govern the use of the GSA SmartPay® **travel** card/account, as well as understand my role and responsibilities as **an agency/organization program coordinator (A/OPC)** as outlined in this training course.” 

Purchase Training for Agency/Organization Program Coordinators (A/OPCs): 
☑ “I acknowledge that I’ve read and understand the policies and regulations that govern the use of the GSA SmartPay® **purchase** card/account, as well as understand my role and responsibilities as **an agency/organization program coordinator (A/OPC)** as outlined in this training course.” 

Fleet Training for Agency/Organization Program Coordinators (A/OPCs): 
☑ “I acknowledge that I’ve read and understand the policies and regulations that govern the use of the GSA SmartPay® **fleet** card/account, as well as understand my role and responsibilities as **an agency/organization program coordinator (A/OPC)** as outlined in this training course.” 

Travel Training for Card/Account Holders and Approving Officials (AOs):
☑“I acknowledge that I’ve read and understand the policies and regulations that govern the use of the GSA SmartPay® **travel** card/account, as well as understand my role and responsibilities as **a card/account holder or approving official** as outlined in this training course.”

Purchase Training for Card/Account Holders and Approving Officials (AOs):
☑“I acknowledge that I’ve read and understand the policies and regulations that govern the use of the GSA SmartPay® **purchase** card/account, as well as understand my role and responsibilities as **a card/account holder or approving official** as outlined in this training course.”

**Comment by JessicaMarine1** [comment]
@A-L33 @johnbeallgsa This is ready for review.

**Comment by A-L33** [comment]
Done!
