### ISSUE TITLE
Accessibility QA of site

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#154]
Before the site goes live, we need to do some manual & automated testing, to ensure the new training site is working expected and accessible:

**Acceptance Criteria:**

- [ ] Run lighthouse
- [ ] 508 testing
   - [ ] [AMP](https://insite.gsa.gov/employee-resources/information-technology/it-accessibility-section-508/accessibility-solutions/accessibility-management-platform-amp?check_logged_in=1) 
   - [ ] [WAVE evaluation tool](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh)

- [ ] Run through each [test scenario](https://docs.google.com/spreadsheets/d/1ZJ4hoqcGbIdP3rm-dNyKTsQwGKxwgXRFAYTKcLTfXP0/edit?usp=sharing) on:
  - [ ] Keyboard
  - [ ] Screenreader

- [ ] Document any issues found

Note: Manual UAT on desktop, desktop (at 200%), and mobile are being handled in #286

**Comment by JessicaMarine1** [comment]
![Image](https://github.com/GSA/smartpay-training/assets/92383362/b5267260-7e10-4bad-9a6c-8097f84870b0)

**Comment by JessicaMarine1** [comment]
Documented issues from AMP in #314. No issues found with Lighthouse

**Comment by brentryanjohnson** [comment]
FYI...the changes in #312 are significant enough that I'll need to go back through and run the tests again on the relevant pages.

**Comment by rebekahperillo** [comment]
Moving to DONE!
