### ISSUE TITLE
Access DAP Analytics (Post-Launch)

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#158]
DAP analytics was added to the site via #132 but until the site goes live, it will be difficult to make sure that the POs know how to access the analytics.

**Acceptance Criteria:**
- [x] After site is in production, ensure SmartPay POs have access to and know how to pull DAP analytics [Note: Andrew knows how to do this; make sure Rebekah has access and knows as well]

**Comment by JessicaMarine1** [comment]
@A-L33 @rebekahperillo it looks like DAP is running and capturing data on all three sites:


![Image](https://github.com/GSA/smartpay-training/assets/92383362/26047163-710b-43c1-a093-c81cc0de784b)

**Comment by JessicaMarine1** [comment]
10/6/2023: confirmed DAP is active on all 3 sites; provided Rebekah instructions to access DAP

**Comment by rebekahperillo** [comment]
I can now access DAP and see the analytics (thank you, Jessica). Moving to DONE!
