### ISSUE TITLE
Training Progress Not Saved

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#16]
As a administrator, I want to notify users that content is not ""bookmarked,"" so users understand that if they navigate away from training without completing a quiz, progress will be lost.

Acceptance criteria:
- Prior to accessing training /quiz, user is provided a message indicating that users will lose progress is the quiz is not completed
- If a user attempts navigate away from the training, a warning is sent indicating that users will lose progress is the quiz is not completed
- If a user attempts to close the browser prior to completing the quiz, a warning is sent indicating that users will lose progress is the quiz is not completed

**Comment by JessicaMarine1** [comment]
Is this story needed? Isn't it not saving progress on the quiz (#18) that is really important?

**Comment by A-L33** [comment]
@JessicaMarine1 Based on the demo that I saw and the pop up that the engineers put in the system, I think we can close this out.  Thank you!
