### ISSUE TITLE
Global design changes

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#174]
- [ ] Update "base" colors
- [ ] Update "primary" colors
- [ ] Update heading font sizing
- [ ] Update heading font families
- [ ] Update heading line heights
- [ ] Update type spacing
- [ ] Update link styles
- [ ] Update button styles
- [ ] Update color of training & quiz banners for purchase (`$theme-color-sp-purchase-medium`) & fleet (`$theme-color-sp-fleet-dark`)
- [ ] When a user selects an answer that is correct, it is highlighted in gray.  If a user selects an incorrect answer, there is no gray highlighting.  Change the design so that any user selected answer is highlighted in gray (https://docs.google.com/presentation/d/1CXmW0nJq9ehc03xjpmXbpzjazEJwCPFXACDK6zslrto/edit?pli=1#slide=id.g24cf8497774_0_22)

**Comment by melchoyce** [comment]
```
/* Theme color overrides */

// Base colors
$theme-color-base-lightest: #F6F7F9;
$theme-color-base-lighter: #E8EBF0;
$theme-color-base-light: #7F8CA3;
$theme-color-base: #566580;
$theme-color-base-dark: #465166;
$theme-color-base-darker: #3E495D;
$theme-color-base-darkest: #2D3544;
$theme-color-base-ink: #1A1F28;

// Primary colors
$theme-color-primary-light: #8DA9E0;
$theme-color-primary: #405E97;
$theme-color-primary-bright: #2753A7;
$theme-color-primary-dark: #1B3973;

// Custom colors
$theme-color-sp-travel-medium: #00467F;
$theme-color-sp-travel-dark: #07385A;
$theme-color-sp-purchase-medium: #900028;
$theme-color-sp-purchase-dark: #640000;
$theme-color-sp-fleet-medium: #00AD8E;
$theme-color-sp-fleet-dark: #005748;
$theme-color-sp-integrated-medium: #CBB778;
$theme-color-sp-integrated-dark: #7E753A;
$theme-color-sp-tax-medium: #C9CCD1;
$theme-color-sp-tax-dark: #4C535D;
```

**Comment by melchoyce** [comment]
```
/* Typesetting */

// Font family
$theme-font-type-sans: "public-sans";
$theme-font-role-body: sans;
$theme-font-role-heading: serif;

// Type scale
$theme-type-scale-lg: 9;
$theme-type-scale-xl: 12;

// Heading font families, custom variables
// H1-H3 use Merriweather
// H4-H6 use Public Sans, so I've made custom variables for them
$theme-h4-font-role: sans;
$theme-h5-font-role: sans;
$theme-h6-font-role: sans;

// Heading line heights, custom variables
$theme-h1-line-height: 2;
$theme-h2-line-height: 3;
$theme-h3-line-height: 3;
$theme-h4-line-height: 4;
$theme-h5-line-height: 4;
$theme-h6-line-height: 3;

// Lead text
$theme-lead-font-role: sans; // custom variable, lead uses Public Sans
$theme-lead-font-size: "lg";
$theme-lead-line-height: 4;
```

**Comment by melchoyce** [comment]
## Buttons

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-8ccc9e25-7fff-a074-ac3d-7cc8ef54a4b9"><div dir="ltr" style="margin-left:0pt;" align="left">

Name | Preview | Properties
-- | -- | --
Button | ![image](https://github.com/GSA/smartpay-training/assets/2846578/7adcdb6a-5dc8-407d-9da6-373b06040297) | BG color: primary
Button:hover | ![image](https://github.com/GSA/smartpay-training/assets/2846578/1a58ec12-f8dd-4c49-afdf-2558397dc774) | BG color: primary-dark
Button:active/focused | ![image](https://github.com/GSA/smartpay-training/assets/2846578/e399c5c5-ae1b-49b0-9fad-e1a3a885e72e) | BG color: base-ink
Button:disabled | ![image](https://github.com/GSA/smartpay-training/assets/2846578/7d8868c2-858d-47b9-90c5-c2489a5e5be9) | BG color: primary / Opacity: 25%
Outline button | ![image](https://github.com/GSA/smartpay-training/assets/2846578/71cf5c7c-6c2e-496d-a99d-23d6c0f83cd9) | Border color: primary
Outline button:hover | ![image](https://github.com/GSA/smartpay-training/assets/2846578/54690762-0bad-4b38-a2cd-3b4d9244d21f) | Border color: primary-dark
Outline button:active/focused | ![image](https://github.com/GSA/smartpay-training/assets/2846578/b9021d69-1407-4098-a43d-3a53908b055e) | BG color: primary-lighter / Border color: base-ink / Color: base-ink
Outline button:disabled | ![image](https://github.com/GSA/smartpay-training/assets/2846578/6852587e-0662-4216-b4aa-8deaeef3daa3)  | Border color: primary / Opacity: 25%

</div></b>

**Comment by klohman** [comment]
Updated color palette based on convo with @mark-meyer on 6/26//23
![image](https://github.com/GSA/smartpay-training/assets/18366192/a07cfa78-7c53-4579-ade2-7210f468d5ba)


/* Theme color overrides */

// Base colors
$theme-color-base-lightest: blue-warm-5 (#ecf1f7)
$theme-color-base-lighter: blue-warm-10 (#e1e7f1)
$theme-color-base-light: blue-warm-20 (#bbcae4)
$theme-color-base: blue-warm-60 (#345d96)
$theme-color-base-darker: blue-warm-70 (#2f4668)
$theme-color-base-darkest: blue-warm-80 (#252f3e)
$theme-color-base-ink: blue-warm-90 (#13171f)

// Primary colors
$theme-color-primary-light: #8DA9E0;
$theme-color-primary: #405E97;
$theme-color-primary-bright: #2753A7;
$theme-color-primary-dark: #1B3973;

// Custom colors
$theme-color-sp-travel-medium: #00467F;
$theme-color-sp-travel-dark: #07385A;
$theme-color-sp-purchase-medium: #900028;
$theme-color-sp-purchase-dark: #640000;
$theme-color-sp-fleet-medium: #00AD8E;
$theme-color-sp-fleet-dark: #005748;
$theme-color-sp-integrated-medium: #CBB778;
$theme-color-sp-integrated-dark: #7E753A;
$theme-color-sp-tax-medium: #C9CCD1;
$theme-color-sp-tax-dark: #4C535D;

**Comment by weiwang-gsa** [comment]
@klohman the last bullet point, what exactly need to be grey highlight, is it the correct answer true need to be highlighted in grey, or You selected: False need to be highlighted in grey? 



![Image](https://github.com/GSA/smartpay-training/assets/119954777/7adafe7a-c136-4a44-9bc8-85a4ea05a1b6)

**Comment by klohman** [comment]
@weiwang-gsa For incorrect answers, the "You Selected" should be highlighted gray.

**Comment by weiwang-gsa** [comment]
@klohman this is ready for design review: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/

**Comment by klohman** [comment]
@weiwang-gsa I noticed a couple things with the new colors. 

- Footer 
    - Background for usa-footer should be base-lighter (#e8ebf0) - it's currently #e1e7f1
    - Background for usa-identifier should be base-darkest (#2d3544)- it's currently #252f3e
    - Visually these look basically the same, but just wanted to note this from this style guide 

- Travel banner color 
    - Background should be $theme-color-sp-travel-medium: #00467F 
        - Looks like it’s using $theme-color-primary: #405E97

The fonts, links, buttons seem to look good (we don't use all of the styles so I clicked around to see what we are using currently). The updates to the quiz answers looks good.

**Comment by weiwang-gsa** [comment]
@klohman Thanks for catching these, I will make changes accordingly, for travel banner color, it is not mentioned in the story, I thought we are not changing existing travel banner color as only purchase and fleet are mentioned in the story. I can certainly change it to the color you want though, just double check.


![Image](https://github.com/GSA/smartpay-training/assets/119954777/53549d09-1e3b-4a49-88f6-b9e02d5d5d3f)

**Comment by klohman** [comment]
@weiwang-gsa Totally understand - the travel banner was omitted and I'm not sure why. It should be changed though to the travel card medium color to be consistent with the other banners. Thanks!

**Comment by weiwang-gsa** [comment]
@klohman I am just checking the base lighter and base-darkest, seems what I have currently are correct based on your previous comment on June 27th. I remembered Mark discuss with you regarding this change around that time for program site. Maybe style guide didn't update accordingly? 



![Image](https://github.com/GSA/smartpay-training/assets/119954777/7d02b45b-d28d-4bc8-b881-7899e9119f77)

**Comment by klohman** [comment]
> @klohman I am just checking the base lighter and base-darkest, seems what I have currently are correct based on your previous comment on June 27th. I remembered Mark discuss with you regarding this change around that time for program site. Maybe style guide didn't update accordingly?
> 
> ![Image](https://user-images.githubusercontent.com/119954777/259548002-7d02b45b-d28d-4bc8-b881-7899e9119f77.png)

Whoops, yes, you're right. I was looking at the original version, so what you have is correct. Sorry for the mistake. Thanks!

**Comment by klohman** [comment]
@rebekahperillo @A-L33 Ready for QA

**Comment by rebekahperillo** [comment]
Looks good. Moving to DONE. Thank you! :)
