### ISSUE TITLE
Administrator | Pre-loading A/OPC Emails for Launch

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#177]
As a system administrator, in order to ensure A/OPCs with reporting access can receive reports at MVP launch, I need to load an approved list of A/OPCs into the system.

Acceptance Criteria:
- [ ] System administrator is able to designate which individuals (emails) are eligible to receive reports
- [ ] MVP will likely need to pre-load accounts (emails) to be able to make these designations
- [ ] System administrators needs to link ^^^ to a specific agency or bureau
- [ ] There may be some overlap with #199

**Comment by JessicaMarine1** [comment]
@A-L33 I think this functionality is part of #186. You can probably delete this issue.
