### ISSUE TITLE
Administrator | Search & Find Users by Name

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#180]
As an administrator, I need to search and find users to assign agencies and bureaus.

Questions/considerations
- Pre-requisite for #199

**Acceptance criteria:**
- [ ] Administrator can search for users by full name, using a not exact search (fuzzy)
- [ ] Results displayed are: full name, email, agency, and bureau
- [ ] Permissions for each user are displayed
- [ ] Limit results to 25 per page

[DESIGN](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1135-24901)

**Comment by weiwang-gsa** [comment]
- How to identify administrators? ( Is there a list of administrators provided?)
- How to navigate to search and find users,  will it display on the top menu if administrator? 
- Does administrator can search and find any user?

**Comment by A-L33** [comment]
The search page is below



![Image](https://github.com/GSA/smartpay-training/assets/116583391/04978292-0093-48ad-aa2c-f2b19ece3a3a)

We only need name, agency, email.



![Image](https://github.com/GSA/smartpay-training/assets/116583391/b2d4ae01-06d9-4c7b-8eaf-1b5c8ccb5744)

What the edit access page looks like.

**Comment by JessicaMarine1** [comment]
@A-L33 for the results page, do we want to add bureau so that the AC reads:
- Results displayed are: full name, email, agency & bureau

**Comment by A-L33** [comment]
@JessicaMarine1 Amended the acceptance criteria.  For the reporting permissions, I like the idea of displaying them on the search, should I add that to the AC too?

**Comment by JessicaMarine1** [comment]
yup!

**Comment by melchoyce** [comment]
Will the admin screens eventually contain more tools than just the user lookup, or are we confident we can go straight to this search page after logging in?

**Comment by JessicaMarine1** [comment]
It might eventually contain more, but not for MVP. I think the next team can iterate on design if/when the time comes to add more.

**Comment by melchoyce** [comment]
Sounds good to me!

**Comment by melchoyce** [comment]
> @JessicaMarine1 Amended the acceptance criteria. For the reporting permissions, I like the idea of displaying them on the search, should I add that to the AC too?

What permission information should we include in the results table? "Can view reports?"

**Comment by JessicaMarine1** [comment]
@melchoyce I was thinking a separate column that would display permissions. Thinking ahead for MVP, we might also want to indicate which users have `Admin` permissions as well on the results table. I'm wonder if icons might be worth thinking about here?
Maybe some sort of paper/list icon for those with reporting permissions and a pencil for those with admin access?

**Comment by melchoyce** [comment]
Put together a short video about my current WIP:

https://github.com/GSA/smartpay-training/assets/2846578/45463ea2-92de-440e-b8d2-75ed2318cbc8

[And here's that flow inside Figma](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1008-17786&t=iVUSlqFyhtMavrWm-4).

I made updates to several things since our check-in, including:

1. Removing the email, agency, and sub-agency search fields and just keeping name
2. Increasing the number of results to 25 instead of 10
3. Making the text input fields under edit user disabled
4. Adding the ability to associate multiple agencies/sub-agencies to someone's report access

Related: #199

**Comment by A-L33** [comment]
@melchoyce That looks great.  A few questions for you:

1. There may be a use case where a user could be assigned several "parent agencies" and "bureaus."  In this design, in accounts for multiple parents agencies but not bureaus.  Can we also add multiple bureaus to the design?
2. If we have a bunch of parent agencies and bureaus, does the "add" function become crowded?  Is there a limit to how many I can add?

**Comment by A-L33** [comment]
Another question.  If a user already has permissions, will it look like this after I select the user?


![Image](https://github.com/GSA/smartpay-training/assets/116583391/560a7336-f76a-4ca3-83b6-eb0404a27b3c)

**Comment by melchoyce** [comment]
> 1. There may be a use case where a user could be assigned several "parent agencies" and "bureaus."  In this design, in accounts for multiple parents agencies but not bureaus.  Can we also add multiple bureaus to the design?

Once someone selects an agency, the bureau combobox appears and they can select a bureau. We won't know which bureaus to display until an agency is selected:

![image](https://github.com/GSA/smartpay-training/assets/2846578/68aff21a-9158-46bd-be31-0acc88f4f166)

> 2. If we have a bunch of parent agencies and bureaus, does the "add" function become crowded?  Is there a limit to how many I can add?

Is that something that happens now? How many A/OPCs fall under this particular use case?

> If a user already has permissions, will it look like this after I select the user?

Yup!

**Comment by A-L33** [comment]
@melchoyce If we have a bunch of parent agencies and bureaus, does the "add" function become crowded? Is there a limit to how many I can add? - Is that something that happens now? How many A/OPCs fall under this particular use case?

This is a brand new function, so we're not entirely sure.  But based on what might happen with Treasury, I can see one A/OPC having 10 or more agencies and associated bureaus.

**Comment by melchoyce** [comment]
> This is a brand new function, so we're not entirely sure. But based on what might happen with Treasury, I can see one A/OPC having 10 or more agencies and associated bureaus.

@A-L33 We could save some space by removing the instructions after that first row of options, and hiding the overflow instead of growing the box to show all of the checked items:

**Comment by melchoyce** [comment]
Moved the Figma mockups into the finished page: https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1135-24901&t=iVUSlqFyhtMavrWm-4

**Comment by weiwang-gsa** [comment]
backend method (search-users-by-name) is in place

**Comment by weiwang-gsa** [comment]
@melchoyce @klohman Mark's UI code is in, this issue is ready for design review here: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/admin/

**Comment by JessicaMarine1** [comment]
@A-L33 I think we need to add enough users to be able to test the pagination before calling this done.

**Comment by A-L33** [comment]
27 total users if you search on the term "a."  Pagination works!  Done!
