### ISSUE TITLE
Reporting | A/OPC Accessing Training Reports

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#182]
As an A/OPC, I need to access reporting, so I can view information based on my agency or bureau.

**Pre-conditions:**
- Dependency on #199 being completed -- need to have some users in the DB designated to receive reports

**Acceptance Criteria:**

[Design](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1135-27629)

- [ ] User is able to enter their email address to request a report
- [ ] If the user is _not_ eligible to receive reporting data, they are notified in the UI
- [ ] If the user is eligible to receive reporting data, they will be sent an email with a unique link to access the report
  - Language of email will be addressed in [issue 190] (https://github.com/GSA/smartpay-training/issues/190)
  - Link is only valid for 24 hours
  - If user clicks link within 24 hours, user is brought back into the system where they are presented a button to download the report in CSV
  - If user clicks link after 24 hours, user is provided appropriate invalid/expired link messaging in system

- [ ] Upon pressing download button, user has access to an aggregated CSV report that includes user data (only successful attempts) for all entities (both agency and bureaus as applicable) they have permission to view
- [ ] Reporting fields are:
> - Full Name
> - Email Address
> - Agency
> - Bureau
> - Name of quiz
> - Quiz completed date
- [ ] Data is default sorted by agency and bureau (as applicable)
- [ ] Second data ordered by quiz completion date in newest to oldest

**Comment by JessicaMarine1** [comment]
@A-L33 I think you are missing AC for the part of the flow where the A/OPC makes the request. For example:
- User is able to enter their email address to request a report
- If the user is eligible to receive reports, an email (#190) is sent to the user
- If the user is not eligible to receive reports, ... [error message or #191]

**Comment by A-L33** [comment]
Thank you!

**Comment by A-L33** [comment]
@melchoyce Please share MVP designs.

**Comment by melchoyce** [comment]
![image](https://github.com/GSA/smartpay-training/assets/2846578/198f912b-af31-4583-951d-fcc79d01738f)
[Figma](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=985-14433&t=mYbcFZgCwpUcvWtU-4)

**Comment by A-L33** [comment]
@melchoyce Looks good!

**Comment by A-L33** [comment]
Thank you @JessicaMarine1.  @melchoyce One thought as I'm looking at this.  Could we house the reporting feedback in it's own top nav item?  Putting under "Program Coordinators" might not be intuitive because that's where people might think they access training only.  Thoughts?

**Comment by melchoyce** [comment]
How's this?

![image](https://github.com/GSA/smartpay-training/assets/2846578/df600fda-bac2-493c-a1f4-5fece4fe1404)

@A-L33 re: moving the nav item, my gut is that it makes more sense to group with A/OPCs because it's an item that only they should be accessing. Making it a top-level nav item could confuse people who don't understand who or what the reporting is for, and if it's relevant to them. But I'll also defer to @brentryanjohnson's thoughts on this if he's able to take a look!

**Comment by A-L33** [comment]
@melchoyce Revisions look good.  Interested to see @brentryanjohnson's opinion.  We can also try and test this too.

**Comment by A-L33** [comment]
@melchoyce Quick question.  The link "Not the right email?  Send another email" would send the user back to the page where they enter in their email right?

**Comment by melchoyce** [comment]
> @melchoyce Quick question. The link "Not the right email? Send another email" would send the user back to the page where they enter in their email right?

Yup! Would redirect back to that initial email entry screen.

**Comment by brentryanjohnson** [comment]
@A-L33 @melchoyce I think it makes sense to group reporting under Program Coordinators, for the reasons Mel described. Even though it isn't A/OPC training, it's among the relevant site tasks for that user.

**Comment by mark-meyer** [comment]
I'm not sure if the question in the issue was answered ('Are they brought back into the system where they can download a report?').

When they click on the link in their email, do they come back to the site and then a download starts? or is it a direct link to a csv file? Coming to the site might be needed because there is the possibility that the link they clicked expired and we need a nice way to give them that error.

**Comment by A-L33** [comment]
@weiwang-gsa Let's go with split by bureau (as applicable).

**Comment by brentryanjohnson** [comment]
@melchoyce Since `Reports downloading` is a subheading, it should be title case in accordance with the style guide. `Reports Downloading`

Other than that, I think it looks fine!

**Comment by melchoyce** [comment]
Cool cool, here we go!

![image](https://github.com/GSA/smartpay-training/assets/2846578/1dee2845-0534-477a-bfad-13ce779a390c)
[Figma](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1033-20621&t=iVUSlqFyhtMavrWm-4)

**Comment by A-L33** [comment]
@mark-meyer @weiwang-gsa @jfredrickson5 @rebekahperillo We can discuss at standup tomorrow but we have an interesting situation.  I think have separate reports for each bureau is a good idea and that's what we indicated above.  We just had an interesting situation.  In one agency, there are 2 programs (purchase and travel).  One wants to segregate data by bureaus, the other does not.  Is there a way to generate a separate report for each bureau and have a separate report for the entire agency?  If not, then we may need to change our mind and for MVP generate a single report with bureaus by agency.  Just a thought.

**Comment by JessicaMarine1** [comment]
6/1/2023 Note: the format/design for the reports needs further discussion; scheduled time for the team to discuss on 6/6.

**Comment by melchoyce** [comment]
@brentryanjohnson has had a chance to review the copy and has made some changes:

![image](https://github.com/GSA/smartpay-training/assets/2846578/89013852-1354-47ec-b097-0972880ec2da)
[Figma](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1135-27629&t=iVUSlqFyhtMavrWm-4)

Should be good to go!

**Comment by JessicaMarine1** [comment]
@melchoyce I think we need to update the language on the confirmation "We sent you an email" screen. It makes it sound like they are being sent the reports in the email. Perhaps something like this would work better:

We sent you an email at fred.flintstone@defense.gov with further instructions on how to access the training reports you are eligible to receive.

**Comment by mark-meyer** [comment]
@melchoyce and @A-L33 

In the start page for the quizzes we have the yellow banner saying "This is a U.S Federal Government  system…" _above_ the "Take the GSA SmartPay Quiz" header. In this mockup, we have it _under_ the "Confirm you email…" header. Can we make the reports page match the training page so we can use the same component?

**Comment by melchoyce** [comment]
> In the start page for the quizzes we have the yellow banner saying "This is a U.S Federal Government system…" above the "Take the GSA SmartPay Quiz" header. In this mockup, we have it under the "Confirm you email…" header. Can we make the reports page match the training page so we can use the same component (and for consistency)?

I'll update this!

@brentryanjohnson also suggested "We sent you an email {{ user_input.email }} with a link to download the training reports you requested.", so I'll combine those:

> We sent you an email {{ user_input.email }} with a link to download the training reports you requested. This link is only active for 24 hours

**Comment by melchoyce** [comment]
> In the start page for the quizzes we have the yellow banner saying "This is a U.S Federal Government system…" _above_ the "Take the GSA SmartPay Quiz" header. In this mockup, we have it _under_ the "Confirm you email…" header. Can we make the reports page match the training page so we can use the same component (and for consistency)?

Updated: https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=985-14433&t=iVUSlqFyhtMavrWm-4

Swapping gets kind of weird here, though: 

![image](https://github.com/GSA/smartpay-training/assets/2846578/91c2fe88-f1bb-4e7c-b3f8-2b0dba242865)

Maybe that alert should just be regular paragraph text instead? What do y'all think?

**Comment by A-L33** [comment]
Quick change:  "...with a link to access your training report."  I'm agnostic about whether to use "download" or "access."

**Comment by melchoyce** [comment]
Decided to go with this in our sync today:

![image](https://github.com/GSA/smartpay-training/assets/2846578/c1466477-5218-44aa-b291-975b430cdadc)
[Figma](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1179-27924&t=iVUSlqFyhtMavrWm-4)

**Comment by mark-meyer** [comment]
@melchoyce & @A-L33 question about the above mockup when the email is not authorized. It includes the text "Send another email" but we have not sent an email in this case. Can we make a case that we should leave the email input on this page to the user can see if they had a typo and potentially fix it?

That might look something like this:

![Image](https://github.com/GSA/smartpay-training/assets/7340303/01ff4c5a-848c-4813-b4fa-2518c6576d72)

**Comment by A-L33** [comment]
Yeah, I like this idea.  Can we play with the language or lay out a little?  Maybe use language like "Confirm that you entered the correct email?"  I want to convey that if you are getting this message and your email is correct, you don't have authorization and you should contact our team for assistance.  Just some thoughts.

**Comment by melchoyce** [comment]
Agree re:copy. Tried a first stab at some text, but feeling eh about it—would love to have @brentryanjohnson gut check next week:

![image](https://github.com/GSA/smartpay-training/assets/2846578/d1bfbd6a-bc54-4119-bb7b-7c2ab54f45fd)

**Comment by weiwang-gsa** [comment]
@A-L33 Questions:

1. What is CSV file name will be?  e.g. UserQuizCompletionReport.csv ? or whatever you want to name it. 
2.Just to confirm, column name is in Camel case : 

- Full Name
- Email Address
- Agency
- Bureau
- Name of Quiz
- Quiz Completed Date ( Or Quiz Completion Date? ) What is the date format you want it to be? e.g. June 12, 2023 or 06/12/2023?

**Comment by A-L33** [comment]
@weiwang-gsa Can we name is "SmartPay Training Quiz Completion Report?"  Is there an advantage or disadvantage for file or column name casing?  Happy to take a recommendation here.

Good with Quiz Name and Quiz Completion Date.  Please use MM\DD\YYYY format.

**Comment by weiwang-gsa** [comment]
@A-L33 We usually avoid empty space in a file name, common practice is to user underscore or dashes, e.g. SmartPay_Training_Quiz_Completion_Report.csv  or SmartpayTraningQuizCompletionReport.csv. To me, CamelCase usage is for readability. Also, As in story desc, some of column are using camel case, some are not, just want to be consistent. Maybe @brentryanjohnson has more input regarding file name or column name?

**Comment by A-L33** [comment]
@mark-meyer @weiwang-gsa Can you add me as a reporting user?  I tried to use andrew.lee@gsa.gov and I wasn't authorized.  Thank you!
