### ISSUE TITLE
Administrator | Version Control

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#187]
As an administrator, I want to be able to track the changes made to the system.

Questions:
- Discuss with team.  Maybe this is process based outside of the system.

Acceptance Criteria:
- Implement change control process
- Change control system?

**Comment by JessicaMarine1** [comment]
@A-L33 I think this _could_ be achieved through Release Notes. Take a look at what we're doing on the [PBS workplace build](https://github.com/GSA/wp2030-microsite/tags). At each release, there is a summary of changes and a snapshot of the code captured at that time.

**Comment by JessicaMarine1** [comment]
6/7/2023: per @A-L33 Release Notes are sufficient for version control.
