### ISSUE TITLE
Email | User Retrieving Certificates

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#189]
As a user who has previously passed a quiz, I want to retrieve a certificate.

**Flow is complete, this story only updates the content of the email/subject line and fixes a bug in bold below.**

**Acceptance criteria:**

- [x] When a user requests past certificates _and_ is already in the system, an email is sent to the registered user with a URL link to access past certificates
- [ ] Content of email is available at https://docs.google.com/document/d/1p3lakO5V08vHXcKo0LkhzVTcNQYupbEMv6Zo_VHJmfk/edit
- [ ] Update email subject line to: Access your GSA SmartPay training certificate(s)
- [x] The unique and secure URL link is sent to user should only be active for 24 hours.
- [x] User is aware the link is only going to be valid for 24 hours
- [x] If user clicks on URL after 24 hours, user is routed to an page that let's them know the link is expired or invalid (similar to quiz link flow)
- [x] If the user clicks on the URL within 24 hours, the user is routed to a page that displays user's past certificates(already completed [issue 27](https://github.com/GSA/smartpay-training/issues/27))
- [ ] **Correct the email link bug as documented from Wei below**

**Comment by A-L33** [comment]
@brentryanjohnson Email is ready for your review!

**Comment by weiwang-gsa** [comment]
@A-L33 @rebekahperillo  No design change involved. This is ready for QA ( You may need to clear your cache): https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/

**Comment by A-L33** [comment]
Done!
