### ISSUE TITLE
Email | Confirmation for A/OPC Pulling Reports

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#190]
As an A/OPC, if I am authorized, I want to access reporting information, so I can retrieve a training report.

**Acceptance criteria:**

 - [ ] If an A/OPC is authorized to access reporting information, an email with unique link is sent to the authorized A/OPC upon request (see #182)
 - [ ]  Content of email is available at https://docs.google.com/document/d/1ckLo8bw0_e0GR_9fMBN0rskteumkguU8WDu6Ah7ZEvo/edit
 - [ ] Email subject line: Access to GSA SmartPay training report
 - [ ]  A unique and secure URL link sent to user should only be active for 24 hours.
 - [ ]  User is aware the link is only going to be valid for 24 hours
 - [ ]  If user tries to access link after 24 hours, user is presented with appropriate expired link error messaging (similar to quiz access and past certificate flows)

**Comment by A-L33** [comment]
@brentryanjohnson Ready for your review!

**Comment by brentryanjohnson** [comment]
✅ Reviewed @A-L33

**Comment by A-L33** [comment]
Ready for development.

**Comment by weiwang-gsa** [comment]
Q: How to get A/OPC authorized?

**Comment by A-L33** [comment]
@weiwang-gsa Through #199.

**Comment by weiwang-gsa** [comment]
@A-L33 @rebekahperillo  No design change involved. This is ready for QA ( You may need to clear your cache): https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/

**Comment by A-L33** [comment]
Done!
