### ISSUE TITLE
Email | Unauthorized User Pulling Reports

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#191]
As an administrator, I want to send an email to users making an unauthorized attempt to retrieve reporting information.

**Acceptance criteria:**
- [ ] An email is sent to a user making an unauthorized attempt to access reporting information
- [ ] Content of the email is available at https://docs.google.com/document/d/1bUX4oQU08qARLQLZr0Xasc_HsBxvvM8XGMrOFoVrqOw/edit

**Comment by A-L33** [comment]
@brentryanjohnson Ready for your review!

**Comment by brentryanjohnson** [comment]
✅ Reviewed @A-L33

**Comment by A-L33** [comment]
Ready for development.

**Comment by JessicaMarine1** [comment]
Is is necessary for the system to send an email in this situation, or could it check the database and, if the user's email is _not_ on the approved list, provide an error message when the user inputs their email address (much like the retrieve past certificates flow)?
