### ISSUE TITLE
Administrator | Associate A/OPCs with Multiple Agency/Bureau for Reporting

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#199]
As an administrator, I need to grant A/OPCs access to reporting information for more than one agency and more than one bureau.

Considerations:
- #180 is a prerequisite
- Options for multi-select:  https://github.com/18F/all_sorns/issues/65 and https://github.com/18F/all_sorns/pull/140
- Working example of multi-select (shows up after initial search): https://sorndashboard.fpc.gov

**Acceptance Criteria:**
- [ ] Administrator can edit each user to grant permission for accessing reporting for more than one agency or bureau
- [ ] System saves assigned permissions for agency(s) and bureau(s) to specified user

[DESIGN](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1135-24901)

**Comment by melchoyce** [comment]
@klohman did a bunch of good iterations on this to address some overall UX confusion, and along with @mark-meyer we've updated this UI:

![image](https://github.com/GSA/smartpay-training/assets/2846578/6630cd84-ed4c-4a20-9945-98e9c0584ddc)

It'll work a little more like https://sorndashboard.fpc.gov/, and we won't need to hack the combobox component with this approach.

@A-L33 does this work for your team? Can also demo it for you if that's easier.

**Comment by A-L33** [comment]
@melchoyce If you don't mind doing a demo, that might help.  A little hard to track through static design pages.

**Comment by A-L33** [comment]
@rebekahperillo Thoughts here?  @melchoyce That looks great.

**Comment by rebekahperillo** [comment]
@A-L33 @melchoyce Looks great! 

Once agency is selected, should the next dropdown read "Filter by sub-agency/bureau" or something like that?

**Comment by klohman** [comment]
Design tweaks per our discussion at standup with @mark-meyer, @JessicaMarine1  

cc. @A-L33, @rebekahperillo 

### When agency has multiple bureaus 

![Image](https://github.com/GSA/smartpay-training/assets/18366192/6fce68ef-44e4-40a1-89c7-acb0dcb416f6)

* Display a "Select All" button 
* On click of Select all - all bureaus are checked and added to the table on the right 
* Update label on filter/search field to "Filter by sub-agency name"

### When agency has no bureaus 
![Image](https://github.com/GSA/smartpay-training/assets/18366192/a162cd54-8f15-4412-8256-6fdf62d06e2b)

* Hide the filter by sub-agency search field 
* Hide Select All button 
* Agency name displays again with checkbox

**Comment by klohman** [comment]
@mark-meyer @weiwang-gsa 

Super small design tweak- the "select all" link should be "Select all" 

![Image](https://github.com/GSA/smartpay-training/assets/18366192/bab04ca0-5a29-44cc-87b7-70a456ad6ce4)

**Comment by mark-meyer** [comment]
Thanks @klohman this should be updated now!

**Comment by JessicaMarine1** [comment]
@A-L33 ready for your 👀

**Comment by A-L33** [comment]
Awesome work on this everyone!  The design and engineering on this and #182 are phenomenal.  My only regret is that only people on my team get to see the amazing work.  Done!
