### ISSUE TITLE
BUG: `Submit another email` link results in 404 error

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#201]
Current behavior: After a user submits their email address to request access to a quiz (or past certificates), there is a link to `Submit another email` on the confirmation screen. When you click on this link, you get a 404 error. [Recording](https://github.com/GSA/smartpay-training/assets/92383362/cba1876e-7f54-4ab3-9c16-43046b319b2c)

Expected behavior: Upon clicking the `Send another email` link, you are routed back to the preceding form page to re-enter an email.

**Comment by A-L33** [comment]
Done!
