### ISSUE TITLE
Registration | Change Name to Full Name

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#202]
Across the site, whenever a user is prompted to enter their name, change the label on the field from "Name" to "Full Name"

![Image](https://github.com/GSA/smartpay-training/assets/116583391/f546d978-6da3-42ec-afbd-cd6b7d6f8c37)

**Comment by weiwang-gsa** [comment]
@klohman this is ready for design review: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/

**Comment by klohman** [comment]
@rebekahperillo @A-L33 Ready for QA

**Comment by rebekahperillo** [comment]
Great, moving to "DONE"! Thank you!
