### ISSUE TITLE
Administrator | Search & Find Users by Email

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#203]
As an administrator, I need to search and find users by email to review/edit the user's profile.  Related to #180.

**Acceptance Criteria:**

- [ ]  Administrator are able to search for users by name or by email in the search box.
- [ ]  Results displayed once search takes place remain unchanged - full name, email, agency, bureau (as applicable) and access (where reporting access is indicated).

**Comment by CodyHinze** [comment]
**#203 Acceptance Criteria**
 

| Pass/Fail | Description |
| --- | --- | 
| Pass | Administrator are able to search for users by name or by email in the search box. | 
| Pass | Results displayed once search takes place remain unchanged - full name, email, agency, bureau (as applicable) and access (where reporting access is indicated). | 



**Comments/Additional Notes**

-   Additional improvements to the search screen would be for the results be returned in an alphabetical order, have the column headers be sortable


**ADA Compliance (Automated scan via Chrome Lighthouse)**

| Criteria | Score |
| --- | --- | 
| Performance | 99 |
| Accessibility | 98 |
| Best Practices | 100 |

Tested By Jennifer Davis on 11/6/2023

> Criterial

**Comment by johnbeallgsa** [comment]
Looks good. Moving to done.
