### ISSUE TITLE
Email addresses should be case insensitive

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/smartpay-training#208]
The system currently treats emails as case sensitive. As a result, differing capitalization results in separate user records.

**Acceptance Criteria:**

- [ ] Emails in the training system should be case insensitive
- [ ] Ensure emails in administrator table are lower case _and_ case insensitive
- [ ] OK to wipe existing database

**Comment by weiwang-gsa** [comment]
@klohman this is ready for design review, please note staging is link to brand new DB, so there is no existing user account, you need to first create your account, and then verify if it is allow case sensitive or not. : https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/

**Comment by klohman** [comment]
@rebekahperillo @A-L33 Ready for QA.

**Comment by rebekahperillo** [comment]
Looks good, moving to DONE. Thank you!
