### ISSUE TITLE
Audit logging for administrator activity

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/smartpay-training#210]
Log administrator activity, specifically:
- When an admin logs in and out
- When an admin performs privileged functions (e.g., add/edit/delete users and roles)

Some related controls, there are possibly more:
- AC-2
- AU-2
- AU-6
- CA-7

Acceptance criteria:
- [ ] Need to demonstrate the following:
- When an admin account logs in and out
- Who added, edited, or deleted an account and when
- Who added, edited, or deleted an account's role(s) and when

**Comment by jfredrickson5** [comment]
Note that cloud.gov gives us access to an ELK stack that logs application stdout: https://logs.fr.cloud.gov/

Could be as simple as logging activity to stdout, then creating a dashboard in Kibana to filter out the specific events we want.

**Comment by rebekahperillo** [comment]
Jessica confirmed with Jeff that all our activity was logged appropriately. Moved to done, thank you!
