### ISSUE TITLE
Audit logging for A/OPC and account holder activity

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/smartpay-training#211]
Log A/OPC and account holder activity in the system, such as:
- When a confirmation email is requested
- When someone uses a confirmation email link to access items such as quizzes, reports, etc

Some related controls, there are possibly more:
- AU-2
- AU-6
- CA-7

Acceptance criteria:
- [ ] Ability to demonstrate the following:
- When someone requests an email confirmation link to be sent to them (what email address and when)
- When someone clicks on an email confirmation link (what email address and when)
- What activity the email confirmation link led to (e.g., take a quiz, generate an A/OPC report)

**Comment by rebekahperillo** [comment]
Jessica confirmed with Jeff that all our activity was logged appropriately. Moved to done, thank you!
