### ISSUE TITLE
Reporting Fields

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#22]
As an A/OPC, I want access to the following information by designated time period, so I can access details of training.

Acceptance criteria:
- Reports include the following:
   1)  Name
   2)  Agency
   3)  Bureau
   4)  Quiz completed date
   5)  Name of quiz
   6)  Link to certificate (nice to have, if possible)

**Comment by JessicaMarine1** [comment]
- Currently have 376 A/OPCs who can login and access information for their specific agency.
