### ISSUE TITLE
Update quiz email language

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#222]
Based on user feedback, update the email subject line & language that is sent to users when requesting access to quiz below.  This is just the email language for the completed story #52 :

SUBJECT: Access GSA SmartPay [_name of quiz_] quiz

[Hello User’s name],

Click on the link below to access the [_name of quiz_] quiz.

[Generated link]

This link will expire in 24 hours.

If you did not submit this request, you may be receiving this message in error.  Please disregard this email. If you have any questions or need further assistance, email us at [gsa_smartpay@gsa.gov](mailto:gsa_smartpay@gsa.gov).

**Comment by weiwang-gsa** [comment]
@A-L33 @rebekahperillo  No design change involved. This is ready for QA ( You may need to clear your cache): https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/

**Comment by A-L33** [comment]
Done!
