### ISSUE TITLE
Agency Training Reports [After Grooming, maybe DELETE]

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#23]
As an A/OPC, I want to access training information for an entire agency and bureaus (as available) or by bureau only, so I can track training compliance for my program.

Acceptance criteria:
- User is able to access training reports by submitting email
- The submitted email is verified against a list of authorized users in the system (program will provide final list)
- If the email is confirmed, the user is taken to a page where they can access reporting information based on permission
- If the email is not confirmed, the user is shown a message indicating, "The email provided has not been approved to access training reports.  For more information, please contact your agency's Level 1 A/OPC and gsa_smartpay@gsa.gov."

**Comment by melchoyce** [comment]
@A-L33 Could I have you try accessing these from a different browser? They should be set to "anyone can view" 😩

**Comment by A-L33** [comment]
@melchoyce Looks great!  During the next grooming, we'll get in this more.  I would love to have a report filter, but wanted to chat with the developers about it.  It's not currently in the story due to LOE concerns.

@mark-meyer Mel asks an interesting question about having a "not authorized" message versus being emailed one.  Thoughts?

**Comment by A-L33** [comment]
Story has been folded into other stories.
