### ISSUE TITLE
Certificate | Email Certificate

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#232]
As a user, I would like to have a copy of my certificate emailed to me in PDF form once I complete a training, so that I have easy access to the document if my management requests it.

**Acceptance Criteria:**
- [ ] Upon passing a quiz, the user is automatically emailed a certificate in PDF.
- [ ] The system will use the email on record.
- [ ] The text of the email will be TBD.

**Comment by rebekahperillo** [comment]
Discussed this story with Tri/Enechi on 11/7/23. They had no concerns from a security perspective.

**Comment by JennaySDavis** [comment]
**#232 Acceptance Criteria**
 

| Pass/Fail | Description |
| --- | --- | 
| Pass | Upon passing a quiz, the user is automatically emailed a certificate in PDF|
| Pass |The system will use the email on record| 
| Pass | The text of the email, below|
Hello [Name],

Congratulations!

You've successfully passed the quiz for the [Course Name].

Your certificate is attached below.

If you did not submit this request, you may be receiving this message in error. Please disregard this email. If you have any questions or need further assistance, email us at [gsa_smartpay@gsa.gov](mailto:gsa_smartpay@gsa.gov).

Thank you.esults displayed once search takes place remain unchanged - full name, email, agency, bureau (as applicable) and access (where reporting access is indicated). | 



**Comments/Additional Notes**
N/A


**ADA Compliance (Automated scan via Chrome Lighthouse)**

| Criteria | Score |
| --- | --- | 
| Performance |  |
| Accessibility |  |
| Best Practices |  |

**Comment by rebekahperillo** [comment]
Thanks for passing this along. Is it possible to make these two edits in bold (the text is not to be bolded in the actual email, just bolding here to highlight the proposed updates)? I realized GSA SmartPay isn't referenced.

**Subject: Certificate - GSA SmartPay [Course Name]**

From: [smartpay-noreply@gsa.gov](mailto:smartpay-noreply@gsa.gov)

Hello [Name],

Congratulations!

**You've successfully passed the GSA SmartPay® [Course Name] quiz.**

Your certificate is attached below.

If you did not submit this request, you may be receiving this message in error. Please disregard this email. If you have any questions or need further assistance, email us at [gsa_smartpay@gsa.gov](mailto:gsa_smartpay@gsa.gov).

Thank you.

**Comment by rebekahperillo** [comment]
@felder101 @JennaySDavis @CodyHinze @johnbeallgsa @LoraBradford Checking in on the above comment. Is it possible to make these two edits? Thank you!

**Comment by felder101** [comment]
@rebekahperillo How does this look?




![Image](https://github.com/GSA/smartpay-training/assets/30899941/c166558d-3e56-4ac9-8c52-d47add15e5f2)

**Comment by felder101** [comment]
Removed bolded text.

![image](https://github.com/GSA/smartpay-training/assets/30899941/6778c562-4978-4979-84e8-f8910161f6ae)

![image](https://github.com/GSA/smartpay-training/assets/30899941/b160c501-38a9-4d48-9723-ca38b7fd70e7)

**Comment by LoraBradford** [comment]
All quizzes have been completed and an email was received with the correct wording. John verified the travel and purchase card/account holders & approving officials training and I verified the travel, purchase, and fleet training for program coordinators. 

Moving this to Done! Thank you!
