### ISSUE TITLE
Certificate | Add Agency to the Certificate

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#233]
As a user, I need to have the agency's name visible on the certificate.

**Acceptance Criteria**
- [ ] Certificate includes agency's name [Note: only agency; not bureau]

**Comment by klohman** [comment]
## Design Mock up 

[Figma - Training Site Mockups](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=309%3A4160&mode=design&t=D707yMsjYejRiDU8-1)

![image](https://github.com/GSA/smartpay-training/assets/18366192/c442f4e4-8b31-48d1-af1e-a7213a02be05)

**Comment by mark-meyer** [comment]
@klohman this one should be ready for design review:

https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/

**Comment by rebekahperillo** [comment]
Looks great, thank you! Moving to DONE!
