### ISSUE TITLE
Accessing Training | Exit Session

### ISSUE THREAD

**Issue by rebekahperillo** [GSA/smartpay-training#234]
As a user, I would like to see a message that confirms that I have successfully exited the training website after I select "Exit".

Acceptance Criteria:
- When the user selects "Exit", the following message is displayed. "You have successfully exited."

**Comment by klohman** [comment]
## Design mockup 

[Figma-Exit Success Message - Training home](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=2563%3A41603&mode=design&t=D707yMsjYejRiDU8-1) 

![image](https://github.com/GSA/smartpay-training/assets/18366192/9059fdcc-c23c-4af6-b67e-33571c46df1c)

**Comment by mark-meyer** [comment]
@klohman This is ready for a design review. You should see the banner when exiting on the staging branch:

https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/

**Comment by klohman** [comment]
@rebekahperillo @A-L33 Ready for QA!

**Comment by rebekahperillo** [comment]
@klohman It looks like we're missing a "to" after "or", so that it reads "You have successfully exited your session. You can start a new session to take another training or to access your certificates."

I've read it several times now and would like your opinion. Do you think we need the "to" or do you think it's ok as is?

Thanks!

**Comment by klohman** [comment]
@rebekahperillo I think you're correct and we should update the text. 

@mark-meyer Can you change the text for the alert to "You have successfully exited your session. You can start a new session to take another training or to access your certificates."

**Comment by mark-meyer** [comment]
@rebekahperillo This has be updated and the text in the alert should not have the other `to`.
https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/

**Comment by rebekahperillo** [comment]
@mark-meyer Sorry, one more thing. May I have reporting access in staging? I'd like to see what message displays there when I exit a session. I wonder if I need to include language for reporting in the statement below. Something like:

"You have successfully exited your session. You can start a new session to take another training, to access your certificates, or to access reports (Level 1 A/OPCs only)."

**Comment by mark-meyer** [comment]
@rebekahperillo I think you are an admin on the site, so you should be able to give yourself reporting access by logging into https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/admin

I am not an admin, so to do that I would need to manually update the DB, which is something we try to avoid (it's easy to break things doing that) if there's a route through the UI. 

I also wonder if we could pull @brentryanjohnson in for a second set of eyes here. People who have exited a session have just demonstrated that know how to take a quiz/access-cert/get-reports. Do we need to tell them that they can do that again, or is it enough to alert them that they have exited? Also, we all know what a session is, but does telling a user to start a new session mean anything to them (we don't have any links or buttons to start a new session)?

**Comment by rebekahperillo** [comment]
@mark-meyer I'm getting an error message when trying to access to the provided site as an admin. I'll try again tomorrow after some sleep. I'm guessing it's user error.  :)

I like the simplicity of "You have successfully exited your session." if @brentryanjohnson is open to it.

**Comment by mark-meyer** [comment]
Okay, tomorrow sounds good. We can double check and make sure you are actually in the DB as an admin (and that the admin auth flow is working properly on staging). Have a good night!

**Comment by brentryanjohnson** [comment]
I think the simplest version of the copy is best here, mostly for the reasons @mark-meyer already articulated. As Mark also alluded to, the additional text could even raise more questions than it answers (namely, "What is a 'session'?")

There's another reason to use the simplest version at first, which is that users are much more likely to tell you if they need more information than they are to tell you that a simpler version would have worked just fine for them. Not that we want to make it more likely that users will struggle, but just that you're less likely to know if you _could_ have used a simpler, more concise version if you start with a more verbose, complex version.

**Comment by rebekahperillo** [comment]
@mark-meyer @brentryanjohnson This has been a helpful exercise for me, thank you. Let's go simple. I'll update the text at the top of the page!

**Comment by mark-meyer** [comment]
@rebekahperillo this change is in place now. Also, in the course of debugging the admin login I made made myself an admin on staging and gave you reporting access. We think the we have it working (I can login to the admin page), but we also think the browser may be confused when switching between staging/dev/etc. We'll work with Andrew or you to make sure everything is working.

**Comment by rebekahperillo** [comment]
Looks great, moving to DONE! :) I really like the simplicity. Thank you!

I was able to access reports in staging (thank you!), but still no luck for me with the admin panel (but, I'm tired once again). :)

Thanks for working through the issue with Andrew while I'm away.

Have a good night!
