### ISSUE TITLE
Set Up Staging Branch

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#245]
In order to keep developing during code freeze _and_ after the application is in production, we need to establish a `staging` branch for the training site.

**Acceptance Criteria**:
- [ ] Set up a `staging` branch for the training site

**Comment by JessicaMarine1** [comment]
Information from Arpan:

> Cloud.gov does not have a way to restrict access to environments without the tenant deploying a Web Application Firewall container. Your need to ensure that anything with a friendly DNS name is included in the boundary and scans. E.G. [staging.app.gov](http://staging.app.gov/) if publicly accessible. If behind a waf, or with no DNS assignment, E.G. [crunchypotatodev.app.cloud.gov](http://crunchypotatodev.app.cloud.gov/) we do  not generally include, as these tend to be assigned and vary over time.
> 
> In general, I would say that staging and testing typically are not part of the ATO boundary( but add to network architecture) since they serve different purposes than the production environment. Control SA-3(2) requires pre-production environments be protected at the same level as production environments if live or operational data is used.

**Comment by weiwang-gsa** [comment]
@rebekahperillo @A-L33  staging branch is created based on main branch,  and set as default branch for now during code freeze phase. screenshot provided for QA: 



![Image](https://github.com/GSA/smartpay-training/assets/119954777/dccb2006-7ef9-4686-8fa2-79fa7afbe6ff)

![Image](https://github.com/GSA/smartpay-training/assets/119954777/2f4c69ac-2fb2-4035-981c-d1e292ac59d1)

**Comment by rebekahperillo** [comment]
@weiwang-gsa Great, thank you! :) Moving to DONE!
