### ISSUE TITLE
Issue Training Certificate

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#25]
As a user, I want to receive a certificate after passing a quiz, so that I meet federal and agency requirements for charge card certification.

Acceptance criteria:

- [ ] If the user passes the selected quiz, a certificate is downloaded by the user
- [ ] Certificate has the name of the course passed, and the following information
  - [ ] User's name
  - [ ] Agency name
  - [ ] Date training was completed
  - [ ] CCCM program director's name (currently David Shea)
  - [ ] 1 CLP

Design: https://github.com/GSA/smartpay-training/files/11215004/SmartPay.Certificate.-.Travel.A.OPC.pdf

**Comment by A-L33** [comment]
@johnbeallgsa @brentryanjohnson John, please provide a current certificate to Ryan as an example.

**Comment by johnbeallgsa** [comment]
@brentryanjohnson @actuallyjenn - Please see our current certificate of competition.   


![Image](https://user-images.githubusercontent.com/116584037/228594685-0eb29d98-02b8-4914-b13d-9f57c7abe6ba.PNG)

**Comment by A-L33** [comment]
@actuallyjenn Some feedback from Rebekah:

- Under Director, Center for Charge Card Management, please add General Services Administration as well.
- Please change "has successfully completed the course requirement for" to "has successfully completed the course entitled"
- For the date of the certificate, could we indicate that that's the date the course was complete?  May some text like "completed on" or similar.

**Comment by weiwang-gsa** [comment]
Q: for different quiz completion, will top banner background color and card image stay the same?

**Comment by JessicaMarine1** [comment]
@actuallyjenn Andrew said we should use the version of Dave's signature you used on the design.

**Comment by actuallyjenn** [comment]
Options to review later today at grooming: https://www.figma.com/file/PJzMZ0lk9G6MftrI1PnLN3/Design-Whiteboard?node-id=7-5&t=MmGAzWySlSNDkI95-0

**Comment by actuallyjenn** [comment]
Just to circle back, we went with version 3 in the whiteboard, here is the PDF for the travel card training for A/OPCs 
[SmartPay Certificate - Travel A:OPC.pdf](https://github.com/GSA/smartpay-training/files/11215004/SmartPay.Certificate.-.Travel.A.OPC.pdf)

**Comment by actuallyjenn** [comment]
I've uploaded the 5 certificate variations to [this drive folder](https://drive.google.com/drive/folders/1abmI09JPD-S_5xqdnXQUQWkbJuyseK1f).

**Comment by JessicaMarine1** [comment]
@brentryanjohnson @actuallyjenn One question -- should we include the registered mark in the title of the training on each certificate? I know it's in the "header" but I almost think we need it in the body of the certificate as well.

**Comment by A-L33** [comment]
That works for me @actuallyjenn!

**Comment by mark-meyer** [comment]
I have added the form inputs for `name` and `date` to these and also made a couple tweaks for 508 compliance. These are in the subfolder "[Certificate_Forms](https://drive.google.com/drive/folders/1p1ohn18BhyyzAaJgl_LJZlSPUHXdmcj4)" of the folder above.

**Comment by A-L33** [comment]
Done!
