### ISSUE TITLE
BUG: A/OPC with reporting access gets unauthorized error

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#250]
jessica.marine@gsa.gov has reporting access

Expected behavior: As an A/OPC with reporting access, when I click the link in the email, I expect to be sent into the system to access (download) the report.

Current behavior: When clicking the link in the email, I get an error message telling me I'm not authorized to receive reports.

Video: 

https://github.com/GSA/smartpay-training/assets/92383362/35607140-ca22-49d3-9ff7-07154ff62f89

**Comment by mark-meyer** [comment]
@JessicaMarine1 & @rebekahperillo I believe this is fixed and deployed. I've moved it into QA.

**Comment by rebekahperillo** [comment]
@JessicaMarine1 Thank you! Moving it over now! :)
