### ISSUE TITLE
Update external link icon to only non-gsa.gov sites

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#256]
When we originally implemented the site, we were including the external link icon for any non-training.smartpay.gsa.gov site; this icon should only apply if we're linking to outside of gsa.gov

- [ ] Update external link icon to only non-GSA.gov sites

@weiwang-gsa May have already completed this task on the training system.  Wei will verify.

**Comment by JessicaMarine1** [comment]
Despite OSC's guidance that the external site icon should be used based on where a site is hosted, we decided to take a user-centered approach. A user will not know (or care) if a gsa.gov site is hosted on GSA's drupal instance versus cloud.gov. As a result, we will only implement the external icon for non-GSA.gov sites (based on URL).

**Comment by weiwang-gsa** [comment]
@klohman this is already been implemented as part of home page update, and it is ready for design review: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/

**Comment by klohman** [comment]
@A-L33 @rebekahperillo Ready for QA

**Comment by A-L33** [comment]
Done!
