### ISSUE TITLE
Banner Statement | User Email Addresses

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#258]
As a user, I need to understand how the system will use and store data and to be notified to only use business email addresses.

**Acceptance Criteria:**
- [ ] Update the banner every time emails are solicited, with the statement below:

This is a U.S. General Services Administration Federal Government computer system that is “FOR OFFICIAL USE ONLY.” This system is subject to monitoring. Individuals found performing unauthorized activities are subject to disciplinary action including criminal prosecution.

We only obtain your information necessary to access this system. We collect information such as agency name and email address, to issue training certificates and for agency reporting management. We carefully protect your information and will not make it available to web tracking software for retention. We do not disclose, give, sell, or transfer any personal information about our visitors, unless required for law enforcement or statute.

To access the GSA SmartPay training system, please use your business or work email only, and not a personal email address.

**Comment by A-L33** [comment]
Jackie Henry from the Privacy Office indicated we will not be required to implement this right now.  Closing.

**Comment by JessicaMarine1** [comment]
@A-L33 @rebekahperillo this is ready for your review: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/

New banner should be on:
- quiz registration email entry screen x5
- past certificates email entry screen
- A/OPC reporting email entry screen

**Comment by A-L33** [comment]
Done!
