### ISSUE TITLE
Load Testing

### ISSUE THREAD

**Issue by mark-meyer** [GSA/smartpay-training#264]
Prior to launch we should test the training site to ensure it can handle expected load. We should:

- [ ] Estimate expected peak load (especially the peak number of emails) for a given time frame
- [ ] Create a way to simulate sending emails without burdening GSA's SMTP relay
- [ ] Decide on a load testing framework and implement tests to ensure the system can handle sustained traffic

**Comment by mark-meyer** [comment]
Running some tests on the cloud.gov staging server. 

Here it handles load well when sending actual email.

**Four tests**
- Test 1: scaling to 400 users without sending emails. This is easy for the server DB
- Test 2 & 3: just making sure it is setup correctly
- Test 4: Scaling to 200 users (at a rate of 50 requests/second). It scales fine even through the email server is quite slow (that yellow line). However the email server starts sending errors after about 2000 sent emails.

![Image](https://github.com/GSA/smartpay-training/assets/7340303/1348af3a-8ff2-44a1-95ee-18fee170e45a)

**Errors**

We start seeing this in the logs:
```
2023-08-18T10:06:04.49-0800 [APP/PROC/WEB/1] ERR Message: 'Error sending mail'
2023-08-18T10:06:04.49-0800 [APP/PROC/WEB/1] ERR Arguments: (SMTPServerDisconnected('Connection unexpectedly closed'),)
```
I *think* this is the server protecting itself and realizing we are sending thousands of emails to a single address over s short time (it's actually reassuring that it does this). I am not sure how to test this though since we don't want to send email to random addresses. Trying to use the system immediately after this to send myself (at a different address) a link worked fine. This means we did not hit any sort of global cap and the system continued to operate.

The gmail SMTP relay documentation says we have a daily cap of 10,000 sent emails. 

Running the test again showed the same behavior (although errors started happening around 1700 requests).

**Comment by JessicaMarine1** [comment]
@rebekahperillo @A-L33 Mark conducted load testing on the training site and was pleased with the results (see above). There isn't much to QA on this, so probably ready to be moved to done if you're satisfied with the efforts & outcomes documented.

**Comment by rebekahperillo** [comment]
Moving to "DONE". Thank you!
