### ISSUE TITLE
Add Code Comments to source code

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#265]
As developer, I want to add code comments to the source code wherever it needs more explanation to improve code readability, maintainability and collaboration. 

Acceptance Criteria:

- [ ] Develop of consensus among team on documentation style and conventions
- [ ] The code comments should be concise, clear and relevant to the code they annotate
- [ ] The code comments should help other developers understand the purpose, logic and usage of code functionality
- [ ] The code comments should not state the obvious, but rather provide insights not immediately evident from the code itself.

**Comment by rebekahperillo** [comment]
Moving to DONE!
