### ISSUE TITLE
Email | Check Spam

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#266]
As a user, I need information when I do not receive a confirmation email, so that I can access the training system.

**Acceptance Criteria:**
- [ ] User is provided instructions on every "check your email" page for when an email is sent (5 quizzes, cert retrieval, and reporting).  The example is after a user submits their email on this screen [HERE](https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/quiz/training_travel/)
- [ ] The language should read the following:
"If you have not received the email within 15 minutes, please check your spam folder."

**Comment by weiwang-gsa** [comment]
@A-L33 @rebekahperillo just double check if I just put the new language after "This link is only active for 24 hours."

![Image](https://github.com/GSA/smartpay-training/assets/119954777/cfb2f4a8-68de-4292-8621-4f7edc4eedf8)

**Comment by weiwang-gsa** [comment]
@klohman this is ready for design review, I just put the sentence after this link is only active for 24 hours. https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/

**Comment by rebekahperillo** [comment]
Looks good. Moving to "DONE". Thank you!
