### ISSUE TITLE
GSA Favicon

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#267]
- [ ] Implement GSA favicon

**Comment by klohman** [comment]
Here is what we used on the SP program site: 

16x16
![favicon-16x16](https://github.com/GSA/smartpay-training/assets/18366192/a309daf8-0856-45d3-a5d4-e83b5db57eb0)

32x32
![favicon-32x32](https://github.com/GSA/smartpay-training/assets/18366192/13c8a82b-49be-4c70-9ebf-e0b196a597b0)

**Comment by weiwang-gsa** [comment]
@klohman this is ready for design review: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/

**Comment by klohman** [comment]
@A-L33 Ready for QA!

**Comment by A-L33** [comment]
Done!
