### ISSUE TITLE
Accessing certificates (with email)

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#27]
As a user, I want to retrieve my prior certificates, in case I didn't print/save or can't remember where I saved or filed a previous certificate.

Acceptance criteria:
- From the homepage, user can go through the loginless approach to access an archive of previously-earned certificates
  - Any access link sent to user should expire after 24 hours.
- Each certificate in the archive can be downloaded by the user (same functionality as #25)
- NOTE: if the user is in the system but hasn't earned any certificates, they are presented with a page that states `No training certificates exist for this user`
- If a user's email does not currently exist in the database, a message is provide to the user:
  - Suggested language: "The email address you provided is not currently in the system.  Please check that you have entered an email previously used and that the email address is entered correctly."

**Comment by A-L33** [comment]
I struck part of the original story and revised the AC.  Let me know if you have any questions here.

**Comment by melchoyce** [comment]
Started exploring this flow in Figma: https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?node-id=712-9740&t=ys8TKXk0HliKVGwV-4

Prototype view here: https://www.figma.com/proto/bgNCEcglYMCDtEEBys04cx/SmartPay?page-id=32%3A183&node-id=712-9740&viewport=-3152%2C-3985%2C0.51&scaling=min-zoom&starting-point-node-id=712%3A9740&show-proto-sidebar=1

Some questions:
- Is there any profile information missing that should be included?
- Are there any steps missing from the flow?
- Do we need to include a way to log out/end your current session?
- Should "access certificates" live in the primary navigation, or a secondary navigation within the header, like so?

![image](https://user-images.githubusercontent.com/2846578/233158462-c6631218-5182-4d33-adef-7696f4517fe1.png)

**Comment by JessicaMarine1** [comment]
@melchoyce This looks great!! I think my most immediate feedback is:
- Editing profile info is likely _not_ MVP, so we don't need that functionality on the profile page
- I don't think we necessarily want them to be able to kick off the training flow from their "profile" page so the bottom part re: available training could probably be erased
- We will need to a way to "end session" -- we have another story for that 
- We don't have anything in that upper right-hand corner of the header now, so I like where you have it placed in the prototype
- Should that label on the homepage be `Access past certificates`?

**Comment by melchoyce** [comment]
Great comments—will address and keep you posted!

**Comment by mark-meyer** [comment]
I'm curious about the utility of _viewing_ the certificates vs _downloading_ the certificates. These are PDFs files sent from the backend, so viewing them in something like a modal will require downloading the pdf to the browser, then doing something to convert them to an image for display. Downloading a file is a pretty common thing that the browser will do for us, but displaying it in a modal is going to add quite a bit of complexity.

**Comment by A-L33** [comment]
@mark-meyer If the user is able to see the details of the certificates in a list one their email is confirmed, including when they passed, then I don't see the need to display the cert as opposed to directly downloading, especially if it's going to add complex in the development.

**Comment by JessicaMarine1** [comment]
@mark-meyer I think that this might be attributable to the handoff between Jenn and Mel -- this was supposed to have the same functionality as , which is just downloading the certificate upon clicking the link.

**Comment by JessicaMarine1** [comment]
@melchoyce Apologies for the laundry list, but I think this is a comprehensive list of all the things that I've heard to update:

- [ ] I think we're missing the confirmation ("Check your email") screen after user enters email and hits submit. Maybe mimic what we have for [quiz flow](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?node-id=41-1211&t=tWwnYt51lwpnXwlm-4)
- [ ] Remove the "Didn't receive the access email?" link and any related flow [That will be post-mvp if at all]
- [ ] Remove the ability to edit profile [That will be post-mvp if at all]
- [ ] Remove ability to "view" certificates; user should only be able to download them
- [ ] In the table of certificates, it should include the full name of the training (e.g., "Travel Training for Card/Account Holders and Approving Officials")
- [ ] Remove the "available training" section at the bottom of the profile page
- [ ] Change link and banner language to "Access Past Certificates"
- [ ] Keep language in banner consistent across flow -- "Access Past Certificates"; it shouldn't change on "profile" page  
- [ ] Smaller language on the banner should probably include all user types: Card/account holders, approving officials & A/OPCs
- [ ] On profile page -- will need to be Welcome [full name] since we're only capturing name as 1 field
- [ ] Add additional flow -- user is in the system so they get to "profile page" but don't have any certificates. Consider how to present empty table
- [ ] Error message when user not in system. Maybe @brentryanjohnson has some suggestions for some better language. This was just a first attempt by the PO and he's open to edits.

**Comment by melchoyce** [comment]
Thanks for organizing this, @JessicaMarine1! Makes it much easier to scan through and make updates.

>  Smaller language on the banner should probably include all user types: Card/Account holders, Approving Officials & A/OPCs

Do we have copy for the other user types I can plug in to some examples?

**Comment by melchoyce** [comment]
Would something like this work for users who haven't completed a training yet?

![image](https://user-images.githubusercontent.com/2846578/234051235-0cd53046-f808-49d2-a2cd-6dc9e73c353a.png)

(Copy needs review)

**Comment by JessicaMarine1** [comment]
@melchoyce yes, i think that design works. Where would you see that "Take a training" link going to? Back to the homepage?

**Comment by melchoyce** [comment]
@JessicaMarine1 Yeah, thinking they'd just get dropped back on the homepage.

**Comment by melchoyce** [comment]
I think we just need to finalize copy on these two items, and then we're done:

> The email address you provided is not currently in the system. Please check that you have entered an email previously used and that the email address is entered correctly.

[Figma](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?node-id=712-10024&t=yLEZY9KftiwHbRUu-4)

> You have not earned any certificates yet. Complete a training to earn a certificate.

[Figma](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?node-id=811-8297&t=yLEZY9KftiwHbRUu-4)

@brentryanjohnson can you take a look?

**Comment by JessicaMarine1** [comment]
@A-L33 I'm pulling this one back to in-progress. 

@weiwang-gsa The icon for A/OPC travel isn't working:


![Image](https://user-images.githubusercontent.com/92383362/234348497-0461c5cc-cb83-46f0-8e34-dc254f6886ed.png)

**Comment by mark-meyer** [comment]
@JessicaMarine1  I think this one is on me. Might just have the wrong address for the icons. Should be a quick fix.

**Comment by brentryanjohnson** [comment]
Here's my suggestion based on the SmartPay style guide (see below)...

Minor edit to the first error message:

> We couldn't find the email address you entered. Please check that you entered an email address you've used before and that you entered it correctly.

This one looks good ✅:

> You have not earned any certificates yet. Complete a training to earn a certificate.

---
For reference, here's the voice and tone section from the 🔒 [GSA SmartPay style guide](https://docs.google.com/document/d/19GcaMMf41BdbR5lvZ27c-EHFtAajIdL9qEMtRO0OErY/edit?usp=sharing):

## Voice and Tone
The voice of the GSA SmartPay program is:
- Informational
- Conversational
- Relatable

The GSA SmartPay customer base is diverse.  As such, the program should communicate using federal plain language principles.

We should use first person perspective (e.g., we, you) and active voice, when appropriate.  Active voice helps the reader identify the subject of the sentence and is more direct and concise.

The tone of content may change with the topic being addressed.  Most digital content can be communicated conversationally, however should be more precise when describing legal or technical issues.

**Comment by melchoyce** [comment]
Thanks @brentryanjohnson! I've updated the [Figma](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?node-id=712-10024&t=yLEZY9KftiwHbRUu-4) with that copy change.

**Comment by mark-meyer** [comment]
@JessicaMarine1 & @A-L33 pushing this one back to QA ready. I've incorporated the language change from Ryan and added the missing icons for the card on the certificate page.

**Comment by A-L33** [comment]
Re-done!
