### ISSUE TITLE
Accessibility Feedback | PDF certificates

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#281]
Mark G. Buchko from the GSA IT - Privacy, CUI, 508, Records (IDED) office provided some feedback on the PDF certificates in the training system. 

> I ran the compliance checker on it and found that the form fields for my **Name** and the **certificate Date** were ill formatted.

**Comment by mark-meyer** [comment]
@JessicaMarine1 & @A-L33, the certificates should now pass Acrobat's accessibility checks:

The issue was around tags on the form fields:

![Report](https://user-images.githubusercontent.com/7340303/260864696-c8cedf97-bbb2-4bf6-a307-74da28e350aa.png)

**Comment by JessicaMarine1** [comment]
@A-L33 @rebekahperillo ready for QA. I believe you can move to `Done`. I had Mark G. Buchko, 
Office of the CIO Section 508 Team, re-check the PDF after we implemented the fix and he reports:

> Great Job Jessica!  I'll love to see how accesible it is for Dan next week.  Adobe is identifying it as completely accessible.

**Comment by A-L33** [comment]
Done!
