### ISSUE TITLE
UAT of Training Site

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#286]
The test scenarios are documented [here](https://docs.google.com/spreadsheets/d/1ZJ4hoqcGbIdP3rm-dNyKTsQwGKxwgXRFAYTKcLTfXP0/edit?usp=sharing).

Acceptance Criteria:

- [x] Run through each flow on 
  - [x] Desktop (Joe Novak; SmartPay)
  - [x] _Keyboard_ (covered in #154)
  - [x] Zoom 200% (SmartPay)
  - [x] _Screenreader_ (covered in #154)
  - [x] Mobile (SmartPay)
  
- [x] Document any issues found

**Comment by rebekahperillo** [comment]
@JessicaMarine1 In stand up today, I let the group know that the GSA SmartPay team completed the spreadsheet.

**Comment by JessicaMarine1** [comment]
Thanks @rebekahperillo. The next step would be for you to log any issues found and decide which need to be fixed before launch (MVP) versus those that can wait (post-MVP).

**Comment by A-L33** [comment]
Done!
