### ISSUE TITLE
Loginless Training Access

### ISSUE THREAD

**Issue by johnbeallgsa** [GSA/smartpay-training#3]
As a general user, I want to access required charge card training without logging in, so that I can avoid having to use multifactor authentication.

In the current system, users have the option to take the training first before logging in/creating an account to take the quiz.  I recommend that before allowing access to training/quiz that we confirm email addresses.  We have found that if there are any issues with registration (like email addresses being entered in incorrectly or users not receiving emails), that it's more confusing or frustrating.  It would be a good idea to avoid a situation where a user takes a training/quiz, then enters in an email as if there are any technical issues then, we may lose all progress.

Acceptance criteria:
- Users can access a "registration" function from the homepage [Note: homepage doesn't need to be fully developed, but needs to exist to provide that navigation]
- Users can "register" to access a quiz by providing a valid and active email address
  - Field level validation for emails: follow [USWDS guidance](https://designsystem.digital.gov/patterns/create-a-user-profile/email-address/) 
- Information gathered during registration includes first name, last name, agency, ~~and (as applicable) bureau~~ [move to another story and figure out scope via user research]
  - Use USWDS default field-level validation and error messages (across application) [Mark working on March 6]
  - Parent agency list: https://docs.google.com/spreadsheets/d/1OuL7PV9nsC2c7UKAI-WkzQDsSSf4RHSsGIyU6nfTN3w/edit#gid=1671301105 
- Users are emailed an URL to access quizzes (process similar to what is mapped in this [wireframe](https://docs.google.com/presentation/d/1gM2zHsrjcj4QnF_lN7z7F1xmFeTgP_naxSXk4lL9wI0/edit#slide=id.g147fbb347b7_14_18)) at the provided email address [Note: full content of email will be developed in #9 ]
- Users can use URL to access the quiz (just need landing page; content of quizzes still under development)
- User's first name, last name, agency, ~~bureau (if applicable)~~ & verified email is saved throughout the process

Note: There is (invisible) work that will need to be done to deploy these feature in a sandbox on cloud.gov pages

**Comment by JessicaMarine1** [comment]
@A-L33 Do you have a list of agencies and bureaus that would be used here?

**Comment by A-L33** [comment]
@JessicaMarine1 We'll follow up on the agencies and bureaus.  No restrictions on email addresses and the link sent to the users will be for email confirmation purposes.  No verification required.

If there is another way to provide secure/direct access to confirmed emails, we are open to it.  Doesn't have to be a unique URL.  The registration information just needs to be tied to a user's certificate/training data.

**Comment by JessicaMarine1** [comment]
@A-L33 to insert more background / context

**Comment by JessicaMarine1** [comment]
Not verifying identity behind email; only confirming user has access to (control over) submitted email.

**Comment by mark-meyer** [comment]
One note from USWDS:

> Consider what name information you need. If you don’t need to parse out the separate pieces of a person’s name, consider letting the user enter it into a single full name text field.

Is this something we can/should consider?

**Comment by JessicaMarine1** [comment]
@mark-meyer thank you so much for raising this. 

@johnbeallgsa is there a business reason to capture first and last name and separate fields or should we consider providing one field where the user can enter their full name? In my experience, having only one field for name provides a better user experience.

**Comment by JessicaMarine1** [comment]
@johnbeallgsa in fact, we could ask the user to enter their name as they'd want it appear on their certificate. This would allow for middle names/initials and any suffixes.

**Comment by johnbeallgsa** [comment]
@mark-meyer  @JessicaMarine1 I have one concern about having just one field. We collect email addresses, agencies, and first and last names. When someone can't find their certificate, it usually is because their email changes, for example. UDSA used to be john.beall@fns.usda.gov and now is john.beall@usda.com. When that happens, we search for the user in our database by first and last name. We have many users that we need to be able to break up by first and last name. Or will the user remember precisely what they put in for that column?

**Comment by mark-meyer** [comment]
We will need to deal with the case where users use an old or incorrect link. Right now we are just giving them an unhelpful "not found", but we should probably redirect them to the form again (maybe with a message that the link is invalid or expired). [This is the current state.](https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/#/start-quiz/a08c1516-24c4-4034-b077-6b86fd5f391)

**Comment by JessicaMarine1** [comment]
@mark-meyer I will add ^^^ to #38

**Comment by JessicaMarine1** [comment]
@mark-meyer some UI feedback when comparing the implementation to the prototype:


![Image](https://user-images.githubusercontent.com/92383362/224762328-f732a38c-b2d8-4cc2-907a-bfae4a725350.png)

**Comment by JessicaMarine1** [comment]
Note: Did not implement the agency / organization dropdown using USWDS Combobox due to accessibility issue. Backlogged an new issue [#54](https://github.com/GSA/smartpay-training/issues/54) to reconsider this once the accessibility concern is remediated by USWDS team.

**Comment by JessicaMarine1** [comment]
@johnbeallgsa This one is ready for your QA review!

**Comment by johnbeallgsa** [comment]
Looks good to me.  Moving to done.  Thank you!
