### ISSUE TITLE
Show file type and size for links to non-HTML content.

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#303]
To comply with [USWDS ](https://designsystem.digital.gov/components/link/)guidance, we need to:
**Show file type and size for links to non-HTML content.** 

When possible, create HTML pages instead of linking to files like PDFs. If you do link to a file, tell users ahead of time if the link may trigger a file download, and show the size and format of that file.

We recommend including this information at the end of the link, in the format [FILE_TYPE, SIZE]. We recommend using the file type rather than a product name. Use uppercase for the file type and a comma for the separator. For file size, use the number of pages in the document or the size in MB or KB if the document is not paginated.

_Example 1:_

> GSA published a report, [Transforming the American Digital Experience [PDF, 18 pages]](https://designsystem.digital.gov/files/next/Transforming-the-American-digital-experience.pdf)

_Example 2:_

> Download the [Revised 508 Standards Applicability Checklist [DOCX, 2 pages]](https://assets.section508.gov/files/508-standards-applicability-checklist.docx)

_Example 3:_

> Download the [USWDS 2.11.2 Design Kit for Sketch [ZIP, 13.3 MB]](https://github.com/uswds/uswds-for-designers/releases/download/v2.4.0/uswds-for-designers-v2.4.0.zip)

**Comment by weiwang-gsa** [comment]
@klohman this is ready for design review: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/

**Comment by klohman** [comment]
@A-L33 @rebekahperillo Ready for QA

**Comment by rebekahperillo** [comment]
Looks great! Making it over to DONE. Thank you!
