### ISSUE TITLE
Table Not Rendering Properly on Printable PDF of Travel AOPC Training

### ISSUE THREAD

**Issue by rebekahperillo** [GSA/smartpay-training#310]
As a user, I would like to see the table displayed correctly under "How do I recognize GSA SmartPay travel cards/accounts?" for the travel A/OPC training's printable PDF, as well as on the website. Currently, it only renders correctly on the website. 

The printable PDF that shows the table error is available here: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/training_travel_pc/printable/

**Comment by rebekahperillo** [comment]
@mark-meyer @weiwang-gsa This is what we discussed earlier. Thank you!

**Comment by JessicaMarine1** [comment]
@rebekahperillo can you post a screenshot of what you're seeing on the printable version? I have a compacted table, but it's definitely there:

![Image](https://github.com/GSA/smartpay-training/assets/92383362/23279b34-9654-47a6-ad06-1f0fdf3120c0)

**Comment by rebekahperillo** [comment]
It's there, yes. But the formatting doesn't seem to be displayed as
intended. When Mark, Wei, and I talked about it last Friday, he thought it
may be a bug.

Rebekah Knouse Perillo (she/her)

Lead Business Management Specialist

Center for Charge Card Management
Office of Professional Services and Human Capital Categories
Federal Acquisition Service, U.S. General Services Administration

301-938-5257

***@***.***


Follow the GSA SmartPay program on social media...Tweet with us on Twitter
<https://twitter.com/GSASmartPayNews> and friend us on Facebook
<https://www.facebook.com/GSASmartPayNews/>!
[image: image.png]

**Comment by mark-meyer** [comment]
@rebekahperillo This turned out to be a pretty small change to fix the tables. This fix has a couple side effects: the headings are a little bigger (they now match the site) and (also like the rest of the site) the line-length for the body text is limited to avoid super-long lines and help readability.

https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/training_travel/printable/

**Comment by rebekahperillo** [comment]
Looks awesome, thank you! Moving to DONE!
