### ISSUE TITLE
Bug - Banner Color Correction Needed for Printable Purchase Training

### ISSUE THREAD

**Issue by rebekahperillo** [GSA/smartpay-training#311]
I noticed that the banners for the printable material are not matching the banners for the the types of training on the site.

Example: For purchase, the banner should be red, but it shows as blue. See here: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/training_purchase/printable/

**Comment by weiwang-gsa** [comment]
@rebekahperillo this is ready for QA: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/
