### ISSUE TITLE
Accessibility audit findings

### ISSUE THREAD

**Issue by brentryanjohnson** [GSA/smartpay-training#314]
Here are the accessibility audit findings. I audited the training site with pa11y, Lighthouse, and AMP. All of the issues below were identified using AMP. 

You can find more details from the accessibility audit in the [ 🔒 audit google sheet](https://docs.google.com/spreadsheets/d/1UavK9KiifqARFUqKnlq6GLBNW3niQliwY2GKds2qFjc/edit?usp=sharing).

## Homepage 
[`/preview/gsa/smartpay-training/staging/`](https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/)

### Issue 1
- [x] Done

#### Found

> This A should not contain input elements (without an assigned ARIA role and not type=hidden), keygen elements (without an assigned ARIA role), select elements (without an assigned ARIA role), textarea elements (without an assigned ARIA role) or button elements (without an assigned ARIA role)

#### Element

```
<a class="astro-ZUHOWX7M" href="training_travel/"><button class="usa-button astro-ZUHOWX7M" type="button">Access the travel training</button></a>
```

> [!NOTE]
> This is caused by using a `<button>` element inside an `anchor` element. For accessibility, we shouldn't use a `button` here, since this is link to another page on the website. We should be able to apply the `usa-button` class to the `a` element, and remove the `button` element.

### Issue 2
- [x] Done

#### Found

> This A element has an accessible name of 'access the travel training' that is the same as another A element but doesn't go to the same HREF.

#### Element

```
<a class="astro-ZUHOWX7M" href="training_travel/"><button class="usa-button astro-ZUHOWX7M" type="button">Access the travel training</button></a>
```

> [!NOTE]
> This is caused by using the same text for links that go to different places. We might be able to fix this by adding a more descriptive accessible name to each link via `aria-label`. For example, we might want to distinguish `Travel training for program coordinators` from `Travel training for card/account holders` in the accessible name, since the current link text (if read aloud without the preceding headings) doesn't currently distinguish between them.

## Travel Training Quiz
[`/preview/gsa/smartpay-training/staging/quiz/training_travel/`](https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/quiz/training_travel/)

### Issue 1
- [x] Done

#### Found

> This INPUT has an aria-describedby attribute value of 'email-input-error-message', which includes one or more invalid or duplicate ids

#### Element

```
<input aria-describedby="email-input-error-message" name="email" class="usa-input usa-input tablet:grid-col-8" id="email">
```

### Issue 2
- [x] Done

#### Found

> This fieldset element does not have a mechanism that allows an accessible name value to be calculated

#### Element

```
<fieldset class="usa-fieldset margin-bottom-2"><div class="usa-radio"><input value="0" name="historical-figures" type="radio" class="usa-radio__input usa-radio__input--tile" id="0"><label for="0" class="usa-radio__label">True</label></div><div class="usa-radio"><input value="1" name="historical-figures" type="radio" class="usa-radio__input usa-radio__input--tile" id="1"><label for="1" class="usa-radio__label">False</label></div></fieldset>
```

> [!NOTE]
> There's current nothing that supplies an accessible name to the `fieldset`. Because the quiz question is a heading and outside the `fieldset` element, it isn't connected to the `fieldset` element in an accessible way. Fieldset needs a [`legend` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend) to supply an accessible name that connects it to the radio buttons. The best solution here is likely to wrap the question text in `legend` within the `fieldset`. We might want to consider styling the `legend` element in this context to appear similar to the current `h3` (rather than _also_ using an `h3` inside `legend`).

### Issue 3
- [x] Done

#### Found

> This H4 creates an inappropriate jump in heading levels within the document heading hierarchy

#### Element

```
<h4 class="usa-step-indicator__heading margin-top-0"><span class="usa-step-indicator__heading-counter"><span class="usa-sr-only">Question</span><span class="usa-step-indicator__current-step margin-right-0">1</span><span class="usa-step-indicator__total-steps margin-right-0">of 24</span></span><span class="usa-step-indicator__heading-text">Questions</span></h4>
```

> [!NOTE]
> The `h4` here creates a jump from `h1` directly to `h4`. Since the questions in the quiz are currently `h3`s, this creates a jump from `h1` to `h4` to `h3`, which isn't sequential for accessibility. Since we're dealing with `h3` in a previous issue ☝️, we could either change this step indicator to `h2` or apply the styling to a different element.

### Issue 1
- [x] Done

#### Found

> This ASIDE has an aria-labelledby attribute value of 'summary-box-key-information', which includes one or more invalid or duplicate ids

#### Element

```
<aside aria-labelledby="summary-box-key-information" role="region" class="usa-summary-box padding-y-1 tablet:grid-col-10 border-0"><div class="usa-summary-box__body "><div class="usa-summary-box__text"><p>You can<a class="usa-link" href="./printable">view and print the full Purchase Training for Card/Account Holders and Approving Officials</a>.</p><p>If you have already reviewed the material, you can<a class="usa-link" href="/preview/gsa/smartpay-training/staging/quiz/training_purchase">skip ahead to the quiz</a>.</p></div></div></aside>
```

### Issue 2
- [x] Done

#### Found

> This ASIDE (role=region) does not have a mechanism that allows an accessible name value to be calculated

#### Element

```
<aside aria-labelledby="summary-box-key-information" role="region" class="usa-summary-box padding-y-1 tablet:grid-col-10 border-0"><div class="usa-summary-box__body "><div class="usa-summary-box__text"><p>You can<a class="usa-link" href="./printable">view and print the full Purchase Training for Card/Account Holders and Approving Officials</a>.</p><p>If you have already reviewed the material, you can<a class="usa-link" href="/preview/gsa/smartpay-training/staging/quiz/training_purchase">skip ahead to the quiz</a>.</p></div></div></aside>
```

> [!NOTE]
> We also had this issue with the program website. The default USWDS component uses `aria-labelledby`, but that attribute needs to hook onto an `id` on another element to work properly. We could consider using `aria-label` instead, or connect the current aria attribute to another element that contains descriptive text.

### Issue 1
- [x] Done

#### Found

> This A element has an accessible name of 'external.gsa advantage!' that is the same as another A element but doesn't go to the same HREF.

#### Element

```
<a class="usa-link usa-link--external" href="https://www.gsaadvantage.gov/advantage/ws/main/start_page">GSA Advantage!</a>
```

### ~~Issue 2~~

_Changes in #312 resolved this issue (but introduced others — see comment below)_

#### Found

> ~~This A element has an accessible name of 'external.gsa advantage!' that is the same as another A element but doesn't go to the same HREF.~~

#### Element

```
<a class="usa-link usa-link--external" href="https://www.gsaadvantage.gov/advantage/ws/main/start_page?store=ADVANTAGE">GSA Advantage!</a>
```

**Comment by brentryanjohnson** [comment]
Added comments to #312 about accessibility issues introduced in those changes.

**Comment by brentryanjohnson** [comment]
Additional accessibility issues as a result of merging #312 

## Lesson 1: Purchase Program Overview
`[preview/gsa/smartpay-training/staging/training_purchase/lesson01/](https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/training_purchase/lesson01/)`

### Issue 1

#### Found

Alt text insufficient for alternative description to visual image

#### Element

```
<img src="/preview/gsa/smartpay-training/staging/images/red-card.png" alt="GSA SmartPay card design" width="160" class="margin-y-2">

<img src="/preview/gsa/smartpay-training/staging/images/yellow-card.png" alt="GSA SmartPay card design" width="160" class="margin-y-2">
```

> [!NOTE]
> This `alt` text doesn't distinguish between the two images, and thus insufficient as text alternatives to the visual images. The `alt` text should describe the image in sufficient detail to serve as an alternative to someone who cannot see the image.

## Lesson 3: Preparing to Purchase
[preview/gsa/smartpay-training/staging/training_purchase/lesson03/](https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/training_purchase/lesson03/)

### Issue 1

#### Found

> This A element has an accessible name of 'gsa smartpay website' that is the same as another A element but doesn't go to the same HREF.

#### Element

`<a class="usa-link" href="www.smartpay.gsa.gov">GSA SmartPay website</a>`

### Issue 2

#### Found

> This A element has an accessible name of 'gsa smartpay website' that is the same as another A element but doesn't go to the same HREF.

#### Element

`<a class="usa-link" href="https://smartpay.gsa.gov/content/state-tax-information">GSA SmartPay website</a>`

### Issue 3

#### Found

> This A element has an accessible name of 'gsa smartpay website' that is the same as another A element but doesn't go to the same HREF.

#### Element

`<a class="usa-link" href="https://smartpay.gsa.gov/content/bank-customer-service-centers">GSA SmartPay website</a>`

> [!NOTE]
> AMP flagged these three links with identical text but different link _destinations_. That is, the link text is `GSA SmartPay website`, but the page links go to three different pages. Since assistive technology users can tab through just the links on the page — without the surrounding text — the link text should be descriptive and sufficient on its own to indicate to what specific page the link with take them.

**Comment by weiwang-gsa** [comment]
@klohman @rebekahperillo there is accessibility issue regarding the home page having same link text but actually linked to different pages, any suggestion on the link text update to distinguish them? 


![Image](https://github.com/GSA/smartpay-training/assets/119954777/bcb237fa-8a97-43ff-aa0a-f822b0fd4ef4)

**Comment by klohman** [comment]
@weiwang-gsa @brentryanjohnson 
I like @brentryanjohnson's suggested solution to add more information via the aria-label. Visually, if we change the visible button name it will be redundant, so I'd try the aria-label first.  

> We might be able to fix this by adding a more descriptive accessible name to each link via aria-label. For example, we might want to distinguish Travel training for program coordinators from Travel training for card/account holders

**Comment by brentryanjohnson** [comment]
The reason this is an accessibility flag is because assistive technology users can generate just a list of links on the page, and move through those without having to traverse all of the content on the page. If every link text is the same, there's nothing to distinguish one link from any other when only the links are read aloud (without the accompanying headings or content). For that reason, it would be ideal if we can make the links unique for assistive technology, but keep them visually the same as they are now.

**Comment by weiwang-gsa** [comment]
@rebekahperillo In purchase training, link text "GSA Advantage!" in lesson 4 and lesson 5 are linked to different URL, one is link to : https://www.gsaadvantage.gov/advantage/ws/main/start_page?store=ADVANTAGE and another one is linked to https://www.gsaadvantage.gov/advantage/ws/main/start_page, looks like both rendered with same page, I can't tell there is difference, for consistency, can we have same URL for both? If yes, which one you prefer to use?

**Comment by rebekahperillo** [comment]
@weiwang-gsa What about www.gsaadvantage.gov? :)

**Comment by weiwang-gsa** [comment]
@rebekahperillo I tried with https://www.gsaadvantage.gov, it flashes and change the URL to https://www.gsaadvantage.gov/advantage/ws/main/start_page?store=ADVANTAGE, guess https://www.gsaadvantage.gov/advantage/ws/main/start_page?store=ADVANTAGE is its default one?

**Comment by rebekahperillo** [comment]
Sure, we can go with: https://www.gsaadvantage.gov/advantage/ws/main/start_page?store=ADVANTAGE

**Comment by weiwang-gsa** [comment]
@brentryanjohnson this is ready for your review and re-testing: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/

**Comment by brentryanjohnson** [comment]
@weiwang-gsa It looks like there are still some issues...

## Issue 1
`/preview/gsa/smartpay-training/staging/`

It looks like the `Take the quiz` link text is also the same on each card, so also needs `aria-label` to differentiate each link as unique.

```
<a class="margin-top-2 astro-ZUHOWX7M" href="quiz/training_travel/">Take the quiz</a>
Note
This A element has an accessible name of 'take the quiz' that is the same as another A element but doesn't go to the same HREF.
```

## Issue 2
[`/preview/gsa/smartpay-training/staging/quiz/training_travel_pc/`](https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/quiz/training_travel_pc/)

```
<a aria-haspopup="true" aria-controls="463fa4a9-8ba9-d7cd-5532-d686d64f8dc6-details" class="" id="463fa4a9-8ba9-d7cd-5532-d686d64f8dc6-toggle"><svg class="svg-inline--fa fa-caret-up fa-w-10 fa-3x" viewbox="0 0 320 512" xmlns="http://www.w3.org/2000/svg" role="img" data-icon="caret-up" data-prefix="fas" aria-hidden="true"><path class="" d="M288.662 352H31.338c-17.818 0-26.741-21.543-14.142-34.142l128.662-128.662c7.81-7.81 20.474-7.81 28.284 0l128.662 128.662c12.6 12.599 3.676 34.142-14.142 34.142z" fill="currentColor"></path></svg><span class="ast-offscreen-text">Expand</span></a>
Note
This A lacks an href or a tabindex set to 0 or a positive value.
```

## Issue 3
(quiz)

```
<input readonly="" aria-describedby="email-input-error-message" name="email" class="usa-input usa-input tablet:grid-col-8" id="email">
Note
This INPUT has an aria-describedby attribute value of 'email-input-error-message', which includes one or more invalid or duplicate ids
```

> [!NOTE]
> It looks like this one still has the `aria-describedby` attribute prior to the error state.

**Comment by weiwang-gsa** [comment]
@brentryanjohnson, thanks you, I move it back to in progress, I need to restructure the training card component since we need to add aria-label both for training and quiz link. aria-describedby is due to a typo "s" is accidentally added when working on the other issues, I will also address that as well.

**Comment by weiwang-gsa** [comment]
@brentryanjohnson code update is made, it is ready for retesting: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/

**Comment by weiwang-gsa** [comment]
@A-L33 @rebekahperillo it passed Ryan's review, ready for QA now: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/

**Comment by rebekahperillo** [comment]
Moving to DONE! Thank you!
