### ISSUE TITLE
Check hyperlinks

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#320]
- [ ] Manually check all hyperlinks (after launch) on the training site

**Comment by JessicaMarine1** [comment]
9/13/2023: @rebekahperillo I manually went through all the trainings and updated the URLs to the new program site; we'll still want to check them after launch.

**Comment by rebekahperillo** [comment]
Completed review and submitted a pull request to correct two outdated /non-functioning links. Moving to DONE!

**Comment by JessicaMarine1** [comment]
@rebekahperillo i would recommend keeping the issue I open until those items are fixed. Otherwise, you may lose track of what's still pending versus been fixed.

**Comment by rebekahperillo** [comment]
Will do. :)

**Comment by weiwang-gsa** [comment]
@rebekahperillo your PR is merged into staging and ready for you to QA: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/

Please verify if this is all needed for this ticket, and when you are ready to move it to production. We will have another PR from staging to main once you finished this QA and decided the date for deployment to production.

**Comment by rebekahperillo** [comment]
Looks good on staging, @weiwang-gsa! This is ready to move to production. Would you like me to complete the PR to move to prod with a deployment date? Thank you!

**Comment by JessicaMarine1** [comment]
@rebekahperillo if you're ready, you can open the staging --> main PR to move this production. Please mark @weiwang-gsa as the reviewer. We will also be discussing code flow at our 1pm meeting.

**Comment by weiwang-gsa** [comment]
@rebekahperillo PR is created and I tag you as reviewer. typically once site goes live,  if need to deploy to production, we'll need PO's approval for it. Once you let us know it is ok to deploy to production, we can proceed to next step. Jessica will discuss more regarding this.

**Comment by weiwang-gsa** [comment]
@rebekahperillo This is deployed to production site, please do a final verification in production: : https://training.smartpay.gsa.gov/,  if everything looks good to you,  you can close this ticket as it is shipped, thank you!

**Comment by rebekahperillo** [comment]
@weiwang-gsa Looks great in prod, thank you! CLOSING ticket.
