### ISSUE TITLE
Inconsistent Email Title for Travel Program Coordinator Training Quiz

### ISSUE THREAD

**Issue by rebekahperillo** [GSA/smartpay-training#328]
When a user receives an email with a quiz link, there is an instance of inconsistent email titles.

Specifically, for the Travel Program Coordinator message, the email title and body refer to "Agency/Organization Program Coordinators (A/OPCs)", while for the Purchase/Fleet A/OCP email title and body refer to "Program Coordinators". See images below. 

![Image](https://user-images.githubusercontent.com/133424018/266695745-ae714261-2a4f-4e07-bb16-70aa9f633f13.png)
![Image](https://user-images.githubusercontent.com/133424018/266695744-ac4e0a88-17c1-4c0a-a598-bb05913ed6aa.png)

For now, let's use the reference "Program Coordinators" in all emails.

Acceptance Criteria.
For the Travel Program Coordinator email with a quiz link:
- [ ] Change email title from "Access GSA SmartPay Travel Training for Agency/Organization Program Coordinators (A/OPCs) quiz" to: "Access GSA SmartPay Travel Training For Program Coordinators quiz".
- [ ] Update email body text from "Click the link below to access your GSA SmartPayⓇ Travel Training for Agency/Organization Program Coordinators (A/OPCs) quiz." to "Click the link below to access your GSA SmartPayⓇ Travel Training For Program Coordinators quiz."

**Comment by mark-meyer** [comment]
@rebekahperillo This change should be up and running now.

**Comment by rebekahperillo** [comment]
@mark-meyer Great, moving to DONE! Thank you!
