### ISSUE TITLE
BUG: Return to home link results in 404 error

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#332]
When going through the MFA admin flow as an **unauthorized admin user**, when I got to the "you're not authorized warning" and click `Return to home` I got a 404 error versus being routed back [somewhere]--I would expect to be routed back to the training homepage

**Comment by weiwang-gsa** [comment]
@klohman  this is ready for review: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/

**Comment by klohman** [comment]
@A-L33 @rebekahperillo Ready for QA review
