### ISSUE TITLE
BUG: Secure exit

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#334]
The quizzes do not automatically time out after 30 minutes of inactivity and there is no 5 minute warning message in both desk top and mobile.

**Comment by weiwang-gsa** [comment]
Mark fixed the issue. I changed my mobile settings to let screen auto lock to be "Never", and changed Safri block pop-up to be "Off", I saw the session time out shows up on mobile  below. 

![Image](https://github.com/GSA/smartpay-training/assets/119954777/e3ae00a0-b6cc-4991-8a94-d78eeddae231)

**Comment by mark-meyer** [comment]
@A-L33 this should be ready to test. It should be working on the desktop and as mentioned in mobile, but probably not without changing some settings.

**Comment by A-L33** [comment]
Done with the understanding that experience may vary on mobile devices.
