### ISSUE TITLE
Bug | Label Error in Admin Panel

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#363]
The email field in the admin panel is mis-labeled as "Full Name."  Change to "Email Address."

![Image](https://github.com/GSA/smartpay-training/assets/116583391/ddeb532e-ff2a-439d-a069-9fe937f0bc32)

**Comment by weiwang-gsa** [comment]
@A-L33 @rebekahperillo this is ready for QA: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/
