### ISSUE TITLE
Quiz Clean Up

### ISSUE THREAD

**Issue by rebekahperillo** [GSA/smartpay-training#364]
As I was taking a quiz this morning, I noticed there were some issues where the text did not match the style guide. Here is the document that shows these minor updates:

https://docs.google.com/document/d/1H8BF83d2UTWW2gLUuUs66svg0hCykns7OP-FSMW6TsM/edit

**Comment by rebekahperillo** [comment]
@weiwang-gsa The document is ready for you. Holler if you need anything!

**Comment by weiwang-gsa** [comment]
@rebekahperillo can you give me a little instruction what the change should be? for example, highlight one seems the same as current question, I don't quite sure what exact change that I should make, e.g, from "xxx" to "xxx" would be easier to follow? 


![Image](https://github.com/GSA/smartpay-training/assets/119954777/18016355-0b21-486e-bbd4-947e19826e2d)

**Comment by rebekahperillo** [comment]
@weiwang-gsa I re-shared the document with you. Now that you are an "editor", you can see the suggested edits. :)

**Comment by weiwang-gsa** [comment]
@rebekahperillo @A-L33 This is ready for QA: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/

**Comment by rebekahperillo** [comment]
@weiwang-gsa Hi Wei, there are a few remaining updates. Please take a look at the Google doc and let me know if you have any questions. Thank you!

https://docs.google.com/document/d/1H8BF83d2UTWW2gLUuUs66svg0hCykns7OP-FSMW6TsM/edit

**Comment by weiwang-gsa** [comment]
@rebekahperillo new updates is completed, please review: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/
