### ISSUE TITLE
Link Checker

### ISSUE THREAD

**Issue by rebekahperillo** [GSA/smartpay-training#369]
It looks like we have a link checker on the program website, but not for the training website. If this feature checks whether there are any inactive/dead links every time a PR is processed, it may be a useful tool on the training site as well in order to help keep the content healthy.

**Comment by rebekahperillo** [comment]
@felder101 Any update on how link checker works and whether it is worthwhile to implement on the training website? Thank you!

**Comment by felder101** [comment]
The link checker scans the website links and finds broken links and missing images inside the HTML. I believe there will be limitation if we were to add this to the training site as all pages are not public. The scan appear to only access pages that are public, will not be able to access pages that requires authentication.

**Comment by john-labbate** [comment]
Added to the build pipeline


![Image](https://github.com/GSA/smartpay-training/assets/90406009/3579bc45-070d-4742-948b-9d9a7d5a59a6)

**Comment by JennaySDavis** [comment]
There is no testing of this ticket.  A link checker has been added to the SmartPay Training application and will run on each Training build.
