### ISSUE TITLE
Select Bureau during registration process

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#37]
For CFO Act agency users, there is a need for more granular reporting at the "bureau" level. To accommodate that need, during the "registration" process, users should select a bureau, as needed.

**Acceptance Criteria:**
- When a user selects a parent agency that has available bureaus, those bureaus options are displayed after parent agency selection
- At registration, users must select a bureau after they select a parent agency for:
- Department of Justice

> Bureau of Alcohol, Tobacco, Firearms and Explosives (ATF)
Drug Enforcement Administration (DEA)
Federal Bureau of Prisons (BOP)
Federal Bureau of Investigation (FBI)
Federal Prison Industries (FPI)
Justice Management Division-Offices, Boards and Divisions (OBD)
Office of Justice Programs (OJP)
U.S. Marshals Service (USMS)
Other

- Department of the Treasury

> Alcohol and Tobacco Tax and Trade Bureau
Bureau of the Fiscal Service
Bureau of Engraving and Printing
Community Development Financial Institutions Fund 
Comptroller of the Currency
Financial Crimes Enforcement Network
Internal Revenue Service
Special Inspector General for the Troubled Asset Relief Program
Special Inspector General for Pandemic Recovery
Treasury Inspector General for Tax Administration
United States Mint
Other

- Department of Education
>Departmental Management 
Disaster Education Recovery
Institute of Education Sciences
Office of Career, Technical, and Adult Education   
Office of Elementary and Secondary Education
Office of English Language Acquisition
Office of Federal Student Aid
Office of Innovation and Improvement
Office of Postsecondary Education
Office of Special Education and Rehabilitative Services   
Other

- Department of Transportation
>Federal Aviation Administration
Federal Highway Administration
Federal Motor Carrier Safety Administration
Federal Railroad Administration
Federal Transit Administration
Great Lakes St. Lawrence Seaway Development Corporation
Maritime Administration
National Highway Traffic Safety Administration
Office of Inspector General
Office of the Secretary
Pipeline and Hazardous Materials Safety Administration
Transportation Safety Institute 
Volpe National Transportation Systems Center
Working Capital Fund
Other

- National Science Foundation
> Directorate for Biological Sciences  (BIO/OAD)
Directorate for Engineering  (ENG)
Directorate for Mathematical & Physical Sciences  (MPS)
Directorate for Social, Behavioral & Economic Sciences  (SBE)
Directorate for STEM Education  (EDU)
Directorate for Technology, Innovation and Partnerships  (TIP)
Division of Computer and Network Systems  (CISE)
National Science Board  (NSB)
Office of Budget, Finance, and Award Management  (BFA)
Office of General Council (OGC)
Office of Information & Resource Management  (OIRM)
Office of Inspector General  (OIG)
Office of the Director  (OD)
Other

- General Services Administration
> Federal Acquisition Service
Public Buildings Service  
Office of Administrative Services
Office of Civil Rights
Office of Congressional & Intergovernmental Affairs
Office of Customer Experience
Office of General Counsel
Office of Government-wide Policy
Office of Human Resource Management
Office of Mission Assurance
Office of Small and Disadvantaged Business Utilization
Office Strategic Communication
Office of the Chief Information Officer (GSA IT)
Office of the Chief Financial Officer
Other

-United States Department of Agriculture
>Agriculture Marketing Service
Agriculture Research Service
Animal and Plant Health Inspection Service
Departmental Administration
Economic Research Service
Farm Production and Conservation
Farm Service Agency
Food Safety and Inspection Service
Foreign Agricultural Service
Forest Service
National Agricultural Statistics Service
National Appeals Division
National Institute of Food and Agriculture
Natural Resources Conservation Services
Office of Budget and Program Analysis
Office of Communications
Office of Congressional Relations
Office of External and Intergovernmental Affairs
Office of Hearings and Appeals
Office of Inspector General
Office of Partnerships and Public Engagement
Office of the Assistant Secretary for Civil Rights
Office of the Chief Economist
Office of the Chief Financial Officer
Office of the Chief Information Officer
Office of the Chief Scientist
Office of the Executive Secretariat
Office of Tribal Relations
Risk Management Agency
Rural Development
The White House Liaison Office
Other

**Comment by JessicaMarine1** [comment]
@A-L33 I would recommend re-ordering the bureaus for each agency so that the bureaus are in the alphabetical order

**Comment by A-L33** [comment]
Got it!  Changed.

**Comment by melchoyce** [comment]
How's this? Same combobox behavior as #180:

![image](https://github.com/GSA/smartpay-training/assets/2846578/becb40c8-7ce4-40e3-bd0f-adcaaa387472)

**Comment by A-L33** [comment]
Looks great!

**Comment by A-L33** [comment]
Weird question... do we want an "Other" bureau to be a catch all?  After thinking about it, I don't know if it's something that would be helpful.  Might be something we want to test with the A/OPCs after we build it.  I'm inclined to take out Other... thoughts?

**Comment by melchoyce** [comment]
@JessicaMarine1 and I chatted a bit about the combobox accessibility issues. Because the issues still aren't resolved in USWDS, let's just a regular select box instead for agency (so it remains the same as it is now) and subagency.

**Comment by JessicaMarine1** [comment]
@A-L33 I think this is something that the program needs to decide. Since it will be a required field, are we sure _all_ the options listed (if we exclude "other") will cover all users from a particular agency?
> Weird question... do we want an "Other" bureau to be a catch all? After thinking about it, I don't know if it's something that would be helpful. Might be something we want to test with the A/OPCs after we build it. I'm inclined to take out Other... thoughts?

**Comment by A-L33** [comment]
@rebekahperillo The more I think about this, the more I don't like "Other."  I think either we get rid of it (with the implications Jessica mentioned) or we ask the A/OPCs if they want "Other."

**Comment by A-L33** [comment]
@weiwang-gsa Bureau list is good to go for this story.  I'll include any other agency/bureaus as a new story.

**Comment by rebekahperillo** [comment]
On their site, they say: U.S. Department of Agriculture. I would go with
that.

Andrew, your thoughts?

Rebekah Knouse Perillo
Business Management Specialist
Center for Charge Card Management
Office of Professional Services and Human Capital Categories
Federal Acquisition Service, U.S. General Services Administration

*301-938-5257*
Follow the GSA SmartPay program on social media...Tweet with us on Twitter
<https://twitter.com/GSASmartPayNews> and friend us on Facebook
<https://www.facebook.com/GSASmartPayNews/>!

[image: image.png]

**Comment by A-L33** [comment]
Let's use U.S. Department of Agriculture.

**Comment by JessicaMarine1** [comment]
I'll add this to #209 -- i think we're going to have a few of these agency/bureau clean-up items before launch. Because each one would require a database migration, it's best to make them all at once.

**Comment by weiwang-gsa** [comment]
@A-L33 It is ready for QA: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/

**Comment by A-L33** [comment]
@weiwang-gsa Is it possible to change the order of the bureaus?  They are listed in the acceptance criteria in alphabetical order.  Or should we move this to #214?

**Comment by weiwang-gsa** [comment]
@A-L33 ohh, I thought previously you are talking about Agencies order,  For bureaus, you want the "Other" to be the last item in the bureau list? that is not by alphabetic order then, that will need to introduce new column in table like "sort_order", then it can support the specific order you want item to be displayed on UI. for that case, it will require database structure change and along with all the code update, then it will be better tracked in another story

**Comment by A-L33** [comment]
@weiwang-gsa Understood.  Is there an easy way for the bureaus to be listed alphabetically (we can leave "other" where it shows up on the list for now0?  Or does alphabetizing the bureaus need to be tracked in another story too?

**Comment by weiwang-gsa** [comment]
@A-L33 the code change are made to main branch, bureaus are sorted by alphabetic order now. You may need to clear your cache to see the result change. https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/
