### ISSUE TITLE
Email | Users Accessing Training

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#38]
As an administrator, I want to send an email to registered users, to confirm that the email address submitted has been entered correctly.

This process is not designed to verify the identify of the user, it is meant to confirm that the user's email address is accurate, the email account is in the possession of the user, and the user has access to the email.

Acceptance criteria
- A plain-text email is sent to the registered user with a URL link to access quiz
  - Note: this story is intended to implement the email function 
- The URL sent to the user should be tied to the training / quiz type that the user selected
- Content of the plain-text email is available:  https://docs.google.com/document/d/1UddN5LOg2VBf3g7qbTXV3d4DvLbvT3A_cOZ9wnPuoMc/edit
- URL link sent to user should only be active for **24 hours.**
- User is aware the link is only going to be valid for 24 hours [confirmation screen? email? **both**]
- If user activates URL within 24 hours, the user is authenticated & saved by the system, and routed to start the quiz
**Note:** the URL sent to the user must be unique to the specific training / quiz that the user selected so that the user is routed directly to the start of the selected quiz from the URL
- If user does **not** activate URL within 24 hours, system abandons / clears any system data for URL

Note: We will need to test if the link deactivates after 24 hours. Maybe we can set it to 1 hour for the test; confirm and then increase it back.

**Comment by A-L33** [comment]
@JessicaMarine1 @johnbeallgsa  Content of email added.

@brentryanjohnson Please review content of the confirmation email sent from training system to user as part of the registration process.

**Comment by JessicaMarine1** [comment]
Per Mark's comment yesterday, the URL will only be active for X days. I would think we should include that info in the email as well.

**Comment by JessicaMarine1** [comment]
@brentryanjohnson do you think that we should / need to tell the user that the link is only good for 24 hours in the email?

**Comment by brentryanjohnson** [comment]
Yes, I think we should tell the user that the link will expire and its active duration.

**Comment by JessicaMarine1** [comment]
@brentryanjohnson Please feel free to edit what I added.

**Comment by mark-meyer** [comment]
These edits have been made and we can send html email with issue to allow the link to work. Not sure how to demo this until we get an email server working. But here's a screen shot:



![Image](https://user-images.githubusercontent.com/7340303/227615536-960f4aaa-e215-4917-8e1c-9f8b3af08382.png)

**Comment by JessicaMarine1** [comment]
@A-L33 I think this story is ready to move to `Done`. I tested the email 23 hours after it was sent and the link worked. Testing it after 24 hours resulted in the right error message.

**Comment by A-L33** [comment]
Done!  Thank you!
