### ISSUE TITLE
Radio Buttons USWDS Latest Version 3.6.1

### ISSUE THREAD

**Issue by johnbeallgsa** [GSA/smartpay-training#430]
As a user, I want to see the site less dark on the outline color around the radio button selections on the quizzes. 

The SmartPay training site is using a USWDS default color for this. Based on the user's feedback, USWDS recognized that this color was too dark for some individuals with cognitive disorders. As a result, USWDS has lightened the color of such borders with its latest release -- version 3.6.1

Acceptance Criteria

- update the version of USWDS being utilized on the sites from 3.5.0 to 3.6.1.

**Comment by johnbeallgsa** [comment]
Before (3.5.0):
image.png

After (3.6.1):
image.png

**Comment by JennaySDavis** [comment]
**Acceptance Criteria**
[Pass]  update the version of USWDS being utilized on the sites from 3.5.0 to 3.6.1.

**Comments/Additional Notes**
N/A

**ADA Compliance**

- Performance: 99
- Accessibility: 100
- Best Practices: 100

**Tested By**
Jennifer Davis 11/6/2023

**Comment by johnbeallgsa** [comment]
Moving to done. The site looks great with the latest version.
