### ISSUE TITLE
Training Site Header USWDS

### ISSUE THREAD

**Issue by johnbeallgsa** [GSA/smartpay-training#431]
As a user, I would like to see the header more clearly.  

Acceptance Criteria. 

- Padding the dark grey border (making it wider) and shortening the header to GSA SmartPay® Training to give the user's eyes more space around this particular header

**Comment by johnbeallgsa** [comment]
Currently: 



![Image](https://github.com/GSA/smartpay-training/assets/116584037/dcd7f454-2c20-46d8-a475-b238ba287e83)


Recommendation: 



![Image](https://github.com/GSA/smartpay-training/assets/116584037/9db6a5f6-3d48-4047-9225-14e6b82cf575)

**Comment by JennaySDavis** [comment]
**Acceptance Criteria:** 
[Pass]  Padding the dark grey border (making it wider) and shortening the header to GSA SmartPay® Training to give the user's eyes more space around this particular header

**Comments/Additional Notes:**
N/A

**ADA Compliance**

- Performance:  100
- Accessibility: 96
- Best Practices: 100

**Tested By:**
Jennifer Davis 11/6/2023

**Comment by rebekahperillo** [comment]
@JennaySDavis Padding and title change on staging look great! Just noticed that the Accessibility score is at 96. I thought the goal was to be at 98 or greater. Before moving this to done, should we be concerned about the Accessibility score at 96? Let us know what you think. Thank you!

**Comment by JennaySDavis** [comment]
@rebekahperillo, we can improve upon it.  The accessibility score picked up everything on that page, not just inclusive of the Header change.  I would suggest we create a bug ticket for the accessibility issue found on the page that affected the score. We can link it to this story for tracking purposes, as I would need to work with Dan to determine the development effort to fix the changes needed for the issue listed below. The issue with the page is the following: Elements with visible text labels do not have matching accessible names.

**Comment by rebekahperillo** [comment]
@JennaySDavis #441 has been created to address the bug that lowered the accessibility score. Would you recommend that we move this story to done with the understanding that we'll fix the accessibility issues in a future sprint or should the bug be addressed now before moving the story to done? 

Do you happen to know the accessibility score before the header change? Just curious. Thank you!

**Comment by JennaySDavis** [comment]
@rebekahperillo I did not run any accessibility testing on the screen prior to the change request in this story were executed.

**Comment by rebekahperillo** [comment]
Got it, thank you @JennaySDavis (@johnbeallgsa FYI). 

I'm not sure if you saw my other question.

Would you recommend that we move this story to done with the understanding that we'll fix the accessibility issues in a future sprint or should the bug be addressed now before moving the story to done?

**Comment by JennaySDavis** [comment]
As the AC was met, I would be comfortable moving this story as done. I see the Accessibility issue found as outside of this ticket.

**Comment by rebekahperillo** [comment]
@JennaySDavis Makes sense. @johnbeallgsa, feel free to move to done if you're comfortable in doing so.

**Comment by johnbeallgsa** [comment]
Thank you @JennaySDavis  & @rebekahperillo. I will move this ticket to done with a discussion on bug #441 in the next planning/grooming session.
