### ISSUE TITLE
Typo in Quiz Question for Travel Card/Account Holders

### ISSUE THREAD

**Issue by rebekahperillo** [GSA/smartpay-training#434]
In the quiz for travel card/account holders, there is a typo in one of the quiz questions. It should  be corrected to show 112-194, not 112-19.  

![Image](https://github.com/GSA/smartpay-training/assets/133424018/f5948c4e-7e96-4c1b-b220-25ed4e34b7eb)

**Comment by CodyHinze** [comment]
Contractor to determine new process going forward to handle DB related updates with the SD team. This will require a DBA or authorized users with DB access to run the script that has previously been tested on demo/stage.

**Comment by CodyHinze** [comment]
The script promotion to Stage and Production for data changes will be handled differently then the automatic process that is used for data structure changes. We are working on defining and documenting the standards for this process. The documented process will also need to include defining the responsible person(s) that will be running the script.

**Comment by felder101** [comment]
Database changes have been promoted to stagging via SQL script.

**Comment by JennaySDavis** [comment]
**#434 Acceptance Criteria**
 

| Pass/Fail | Description |
| --- | --- | 
| Pass | Typo in Quiz Question 12 of 24|


**Comments/Additional Notes**
screen shot attached with the updated quiz question content

**ADA Compliance (Automated scan via Chrome Lighthouse)**
This user story includes no new or modified interface features; additional accessibility validation is unnecessary.

Passed 11/28/23 - JSD

![Image](https://github.com/GSA/smartpay-training/assets/149595240/d2e1f155-1f84-4c3d-b667-c1b212953467)

**Comment by johnbeallgsa** [comment]
Current version:  



![Image](https://github.com/GSA/smartpay-training/assets/116584037/bab91380-1200-4399-a9e8-680d13672880)

**Comment by johnbeallgsa** [comment]
Fixed Version. 



![Image](https://github.com/GSA/smartpay-training/assets/116584037/3b84f4dc-57b0-485a-bbd9-f4a1f9632d0e)


Moving to Done. Great Job!

**Comment by johnbeallgsa** [comment]
Prod version. Closing Story. 



![Image](https://github.com/GSA/smartpay-training/assets/116584037/0d79fab6-2873-4623-a5b8-dfe8d94d5179)
