### ISSUE TITLE
Update Language to Reflect that the System is Emailing the Certificate to the User

### ISSUE THREAD

**Issue by rebekahperillo** [GSA/smartpay-training#446]
As a user, once I pass the quiz, I would like the system to inform me that my certificate has been emailed to me and that I have an option to download the certificate on the spot.

Proposed Text Below:

You passed the quiz!

You got X of X questions correct, for a total score of X%, which meets the 75% or higher requirement to pass. 

Your certificate has been emailed to you. Or, you may download your certificate below.

![Image](https://github.com/GSA/smartpay-training/assets/133424018/0dbb31d8-118e-4fb8-8059-da9ea4dadb2e)

@johnbeallgsa @LoraBradford Thoughts?

**Comment by LoraBradford** [comment]
@rebekahperillo I think the wording sounds good!

**Comment by JennaySDavis** [comment]
**#446 Acceptance Criteria**
 

| Pass/Fail | Description |
| --- | --- | 
| Pass | Content Updated|
| Pass | The text of the email, below|

You passed the quiz!

You got X of X questions correct, for a total score of X%, which meets the 75% or higher requirement to pass.

Your certificate has been emailed to you. Or, you may download your certificate below.


**Comments/Additional Notes**
N/A


**ADA Compliance (Automated scan via Chrome Lighthouse)**
This user story includes no new or modified interface features; additional accessibility validation is unnecessary.

Passed 11/28/23 - JSD

**Comment by LoraBradford** [comment]
All quizzes were verified and the wording in the message is correct. John verified the card/account holders & approving officials travel and purchase trainings and I verified the program coordinators travel, purchase, and fleet trainings.

Moving this to done! Thank you!
