### ISSUE TITLE
Training site home page

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#49]
As a training site user, I need to easily access the main workflows from the training site home page, so that I meet my regulatory requirements regarding travel / purchase card training.

Note: The homepage might grow / change as we add more functionality to the site, but this is intended to start building out the training site homepage.

**Acceptance Criteria:**

User can access the following from the training site homepage:
- [ ] Training material for: 
  - [ ] Travel Training for Account Holders/AOs
  - [ ] Purchase Training for Account Holders/AOs
  - [ ] Travel Training for A/OPCs
  - [ ] Purchase Training for A/OPCs
  - [ ] Fleet Training for A/OPCs
    - Note: training material content is still being reviewed / developed by the program, so we can use placeholder content for now if we want to create the separate "child" page for each one
    
- [ ] Ability to kick off the loginless quiz registration process (see #3) for each training type
  **Note:** The system needs to track what training / quiz the user selected bc the URL generated and sent to the user will need to be unique to that specific quiz. 
    
- [ ] Link to GSA SmartPay program site (https://smartpay.gsa.gov/)
- [ ] Contact Us link ([gsa_smartpay@gsa.gov](mailto:gsa_smartpay@gsa.gov))

Design: https://www.figma.com/proto/bgNCEcglYMCDtEEBys04cx/SmartPay?node-id=32%3A186&scaling=min-zoom&page-id=32%3A183&starting-point-node-id=32%3A186&show-proto-sidebar=1

**Comment by johnbeallgsa** [comment]
Mock Draft Design https://www.figma.com/proto/bgNCEcglYMCDtEEBys04cx/SmartPay?node-id=32%3A186&scaling=min-zoom&page-id=32%3A183&starting-point-node-id=32%3A186&show-proto-sidebar=1

**Comment by vickimcfadden** [comment]
For design ☝ in addition to confirming email address in bold, please let users know that the link will expire in 24 hours.

**Comment by JessicaMarine1** [comment]
Removed this AC from this story until we determine what social media, if any, we want to link:

- [ ] Links to GSA SmartPay social media:  [Note: John to confirm which social media accounts are still needed.]  
   - [ ] Facebook (https://www.facebook.com/GSASmartPayNews/)
   - [ ] Twitter (https://twitter.com/GSASmartPayNews)
   - [ ] LinkedIn (https://www.linkedin.com/company/gsasmartpaynews)
   - [ ] Interact (https://interact.gsa.gov/)

**Comment by weiwang-gsa** [comment]
@actuallyjenn I have some questions regarding the mockup:
1. is the header assumption correct? (see screenshot below)


![Image](https://user-images.githubusercontent.com/119954777/225993795-2a2fc6f8-7044-4f8a-9b7f-ca35bc7784af.png)


3. I notice there are headers are all capitals letters, is it on purpose? not sure if it match with smartpay style guide
4. Are we supposed to use USWDS card component (https://designsystem.digital.gov/components/card/)  for this or just normal section (div) with border? I noticed USWDS use buttons, kinda strange coz I remembered in their button section saying if it is pure link don't use button. I just use USWDS card and did quick test below. 
6. Do you have those circle images?

![Image](https://user-images.githubusercontent.com/119954777/225994085-e2369f8a-f4b5-408a-a92e-5daf97ee7fac.png)

**Comment by weiwang-gsa** [comment]
@brentryanjohnson, would you mind confirming the current style guide rule for headers? And let me know what changes I should make, thank you~

**Comment by weiwang-gsa** [comment]
@brentryanjohnson thank you so much!

**Comment by weiwang-gsa** [comment]
@actuallyjenn ready for UI review : https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/

Please let us know if any design change needed. Thanks!

**Comment by JessicaMarine1** [comment]
Reviewed with PO; moving to DONE! Because we're still iterating on the homepage (and full flow) design, we will make any necessary changes in another story.
