### ISSUE TITLE
Kick off quiz from URL

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#52]
As a user who has received an email from the training platform, I want to start my quiz from the URL provided, so that I can have a seamless user experience while complying with my training obligations.

**Acceptance Criteria:**
- If user activates URL within 24 hours, the user is authenticated & saved by the system, and routed to start the quiz
**Note:** the URL sent to the user must be unique to the specific training / quiz that the user selected so that the user is routed directly to the start of the selected quiz from the URL

- If user does **not** activate URL within 24 hours, system abandons / clears any system data for URL
- If a user tries to use an old or incorrect URL link, user should be redirected to the registration form again (maybe with a message that the link is invalid or expired). [This is the current state.](https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/#/start-quiz/a08c1516-24c4-4034-b077-6b86fd5f391)

**Comment by JessicaMarine1** [comment]
Note: if we are moving the name & agency to this page, we'll need to remove it from the registration form currently implemented. Should that be part of this story or a separate, stand-alone story?

**Comment by JessicaMarine1** [comment]
Design: https://www.figma.com/proto/bgNCEcglYMCDtEEBys04cx/SmartPay?node-id=139%3A507&scaling=min-zoom&page-id=32%3A183&starting-point-node-id=139%3A507&show-proto-sidebar=1

**Comment by jfredrickson5** [comment]
@mark-meyer @weiwang-gsa While we're doing this one and refactoring to Astro, let's make sure we also wire up the agency list to the API. The agency list is now available at the `/api/v1/agencies` endpoint, and combined with PR #65, we can pre-populate the database with the list of agencies.
