### ISSUE TITLE
Training Website Content Changes - May 

### ISSUE THREAD

**Issue by CodyHinze** [GSA/smartpay-training#552]
The following content changes need to be made: 

- [ ] Add link to "refunds" text on Travel Training > Program Coordinators > Lesson 01.  

  - Destination URL is "https://youtu.be/5iYRruEPUNM".  
  - Page URL is "https://training.smartpay.gsa.gov/training_travel_pc/lesson01/"
- [ ] Update Four Lesson 1 pages with Visa Card Prefixes 4715 for Purchase and 4615 for Travel Travel. There a no changes to Fleet.
- [ ]  Update Five Lesson 1 pages from 6.5 million total accounts to 4.5 million total accounts.

**Comment by JennaySDavis** [comment]
The following content changes need to be made:

 Add link to "refunds" text on Travel Training > Program Coordinators > Lesson 01.

Destination URL is "https://youtu.be/5iYRruEPUNM".
Page URL is "https://training.smartpay.gsa.gov/training_travel_pc/lesson01/"
 Update Four Lesson 1 pages with Visa Card Prefixes 4715 for Purchase and 4615 for Travel Travel. There a no changes to Fleet.

 Update Five Lesson 1 pages from 6.5 million total accounts to 4.5 million total accounts.

**Comment by LoraBradford** [comment]
Thank you for all of these changes, moving to done!
