### ISSUE TITLE
BUG: Update the GSPC URL

### ISSUE THREAD

**Issue by JennaySDavis** [GSA/smartpay-training#562]
The GSPC URL in production is currently incorrect. The GSPC URL needs to be updated to https://training.smartpay.gsa.gov/admin/gspc/

**Comment by JennaySDavis** [comment]
**#562 Acceptance Criteria**
 

| Pass/Fail | Description |
| --- | --- | 
|Pass |The GSPC URL has been updated to https://training.smartpay.gsa.gov/admin/gspc/ |



**Comments/Additional Notes**
N/A

**ADA Compliance (Automated scan via Chrome Lighthouse)**

| Criteria | Score |
| --- | --- | 
| Performance | 99|
| Accessibility | 100 |
| Best Practices | 100 |



Passed 05/28/2024 - JSD

**Comment by johnbeallgsa** [comment]
Thank you! Moving to Done.
