### ISSUE TITLE
Training | Travel Card Training for Account Holders/AOs

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#57]
As a user of the site, I want to access **Travel Card Training for Account Holders/AOs** without registering, so I can download training materials to review in a 508 compliant format without taking a quiz, or providing my email address.

Pre-Condition:
- Training material [content](https://docs.google.com/document/d/13GupbzWON7SJOWdXHmvOxsdvnQohQXHIzuPJU61fdJk/edit) is complete

Acceptance criteria:
- [ ]  Users can view (in HTML) **Travel Card Training for Account Holders/AOs** without providing an email address
- [ ] Information is presented in an accessible or 508 compliant format
- [ ] Users can access quiz registration form from end of training material

Tentative design: https://www.figma.com/proto/bgNCEcglYMCDtEEBys04cx/SmartPay?node-id=294-772&scaling=min-zoom&page-id=32%3A183&starting-point-node-id=294%3A772&show-proto-sidebar=1

**Comment by JessicaMarine1** [comment]
Save as PDF to be backlogged as new story.

**Comment by JessicaMarine1** [comment]
@brentryanjohnson content ready for your review!

**Comment by brentryanjohnson** [comment]
✅ I took a pass at it!

**Comment by JessicaMarine1** [comment]
@actuallyjenn this content is ready for design.

**Comment by mark-meyer** [comment]
I think the basic structure is in place to parse content once we are ready to start converting the content to markdown.

**Comment by JessicaMarine1** [comment]
Logged issues in #101 Moving `Done`
