### ISSUE TITLE
Training | Fleet Card Training for A/OPCs

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#60]
As a user of the site, I want to access Fleet Card Training for A/OPCs without registering (providing an email), so I can view/print training materials.

**Pre-Condition:**
- Training material content is complete
- Content is available [HERE](https://docs.google.com/document/d/1lcJzEHNJpk8rlT1Kw6PEInXkRV7yTOgYMpisbJ9QLGk/edit)

**Acceptance criteria:**
- [ ] Users can progress through each lesson of the training in the browser without providing an email address
   - Note: this should have the same exact look / experience as the [Travel Card Training for Card/Account Holders & Certifying Officials](https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/training_travel/) (and other trainings already in the system)
- [ ] Users can access quiz registration form from end of training material
- [ ] Users can view & print a 508 compliant, print-friendly version of the full training

**Comment by A-L33** [comment]
@brentryanjohnson Ready for your review!

**Comment by brentryanjohnson** [comment]
@A-L33 Reviewed ✅

**Comment by weiwang-gsa** [comment]
@A-L33 @rebekahperillo this is ready for QA: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/

**Comment by A-L33** [comment]
Done!
