### ISSUE TITLE
Administrator | Edit user's name, agency, bureau, email (DELETE ??)

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#62]
As an administrator, in order to accommodate users who have changes to their information, I need the ability to update a user's name, agency, bureau (if applicable) and email in the system.

*Acceptance Criteria:**
- [ ] Administrator can access the system -- will probably need MFA for this
- [ ] Administrator can search & find a user
- [ ] Administrator can change/edit a user's name, agency, bureau (if applicable) and/or email
- [ ] On save, the user's information in the database is over-written with the new data

Questions for grooming: 
1. We realize this is pretty big; How should this story be broken up?

**Comment by JessicaMarine1** [comment]
@A-L33 @johnbeallgsa Just want to confirm:

- [ ] If we overwrite the user's agency/bureau in the database, the old A/OPC won't have access to the training info of the user while at that original agency/bureau, and the new A/OPC will have access to that user's training while at a prior agency/bureau. Is that the intended behavior?
- [ ] If we change a user's name, any certificate retrieval will show the NEW name on all. Is that the intended behavior?

**Comment by jfredrickson5** [comment]
> We realize this is pretty big; How should this story be broken up?

One possibility:

Story: Integration with SecureAuth login
Acceptance criteria:
- Administrator can access the system via SecureAuth

Story: Search and find users
Acceptance criteria:
- Administrator can search & find a user

Story: Edit user
Acceptance criteria: 
- Administrator can change/edit a user's name, agency, bureau (if applicable) and/or email
- On save, the user's information in the database is over-written with the new data

Also, do we need delete/deactivate user? Maybe as part of the "Edit user" story?

**Comment by A-L33** [comment]
@jfredrickson5 I added the three proposed stories but will keep this one for now until grooming.

**Comment by A-L33** [comment]
@JessicaMarine1 I think this can be deleted.  I've updated the broken up associated stories in 179, 180, and 181.  Concerns before I do?

**Comment by JessicaMarine1** [comment]
@A-L33 nope! I agree the other stories cover it.
