### ISSUE TITLE
Registration Information

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#7]
As a general user, I want to access charge card training courses, so that I can receive certification according to government and agency policies.

Acceptance criteria:
- Users can select and access the following training:
   1.  Purchase Cardholder/AO
   2.  Purchase A/OPC
   3.  Travel Cardholder/AO
   4.  Travel A/OPC
   5.  Fleet A/OPC

**Comment by JessicaMarine1** [comment]
Duplicate -- covered by other stories
