### ISSUE TITLE
End Session | User promtped

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#71]
As a user with an active token, in order to make sure my session ends when I am done, I need a way to end my session.

**Acceptance Criteria:**
- [ ] User is able to end their session
- [ ] Upon ending the session, the browser no longer recognizes the user's session
- [ ] This doesn't impact the user's ability to access email link within 24 hours
- [ ] "Exit" button takes user back to homepage
- [ ] If user attempts to "Exit" (end session) while in the middle of a quiz, user is cautioned/notified in some way -- similar to when they try to close the window/browser mid-quiz

Design:
![image](https://user-images.githubusercontent.com/2846578/235731366-1a0a9d36-19a2-4eee-8b13-212d2a581965.png)
[Figma](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?node-id=32-183)

**Comment by A-L33** [comment]
Based on grooming conversation, explore an "end session" mechanism with an automatic time out.

**Comment by A-L33** [comment]
@melchoyce Adding the "end session" button to relevant pages.  Feel free to play with the language.  Leave?  Sign out?  Exit?  Quit?

**Comment by melchoyce** [comment]
I have two ideas:

## Put it in the nav bar

![image](https://user-images.githubusercontent.com/2846578/235470590-1814a861-15b4-461a-9eb8-55a7d3ba7a39.png)

- Pros: all navigation in one place, easy to find
- Cons: maybe just shoving everything into the navbar is a bad idea?

## Only show on the profile page

![image](https://user-images.githubusercontent.com/2846578/235470864-f03e9d82-086f-462d-b716-a0528ae2d316.png)

Pros: unobtrusive, only shown in the context of being signed in to your account
Cons: need to know it's there, might not remember how to get back to this page since we're not showing it as a logged in profile in the header

For now I'm using "sign out," pending whether it's okay to use that language despite not technically being signed in.

**Comment by A-L33** [comment]
@melchoyce I think it's hard to see for both choices.  Is there a way to make it bigger or more obvious?

**Comment by melchoyce** [comment]
I'd argue that it's not actually an important action (how often do people actively sign out of websites?), but if we need to, we could explore some more prominent designs:

![image](https://user-images.githubusercontent.com/2846578/235475024-f0936773-7f2f-4f64-b748-9fd35f56afdb.png)

**Comment by JessicaMarine1** [comment]
@A-L33 @melchoyce fwiw OLU uses "Exit course" as their end session button.

**Comment by JessicaMarine1** [comment]
What about just "Exit"? That's what HR Links uses lol

**Comment by A-L33** [comment]
I'm good with that!

**Comment by JessicaMarine1** [comment]
@melchoyce Let's just go with "Exit" for now. We can always change it prior (or even post) launch, if needed.

**Comment by A-L33** [comment]
Agreed!

**Comment by melchoyce** [comment]
Will update 👍 

Is the button inside of the nav bar possible with stock USWDS components, do we know? Is that the solution we want to go with?

**Comment by JessicaMarine1** [comment]
@melchoyce one question about the “End session” flow. Does USWDS have any guidance on whether the user should see some sort of warning/confirmation prompt when hitting the “Exit” button _before_ the session ends?

**Comment by melchoyce** [comment]
As far as I can tell, the only time signing *out* is even mentioned is in the [modal documentation](https://designsystem.digital.gov/components/modal/), where it's used as an example of forcing a timeout, which I don't think will apply to use. It does however say: "Use modals sparingly to minimize unnecessary disruptions." I think I'd recommend not using a modal _unless_ someone's in the middle of taking a quiz, in which case we'd want to confirm. How's that sound?

**Comment by JessicaMarine1** [comment]
@melchoyce I think that makes sense and actually follows the pattern we already have in place that they be "warned" when trying to navigate away from the quiz. @A-L33 I will add this as another Acceptance criteria.

**Comment by JessicaMarine1** [comment]
@melchoyce once you've updated the design in Figma, could you please post the appropriate link up in the issue and remove the `Design Needed` tag?

**Comment by melchoyce** [comment]
Can do! Do we need a mockup of the modal flow when exiting during a training, or are we good with what we have?

Also hoping to get a little more feedback re: https://github.com/GSA/smartpay-training/issues/71#issuecomment-1530046879

**Comment by JessicaMarine1** [comment]
Let's ask @mark-meyer. Gonna ping him on Slack.

**Comment by JessicaMarine1** [comment]
@A-L33 ready for your review

**Comment by A-L33** [comment]
Done!
