### ISSUE TITLE
Quiz | Purchase Card Training for A/OPCs

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#77]
As an A/OPC, I want to take the quiz for purchase card training so that I can comply with my regulatory requirements.

Pre-Condition:
- Quiz content is finalized
- Content available [HERE](https://docs.google.com/document/d/11xI5OHCxZtQ5toQf6HFDPK2hF7uXkdhKswkf0gdkFtc/edit#heading=h.nqfy47q0u9sd)

Acceptance criteria:
- [ ] User can "register" for quiz using loginless approach
- [ ] User is sent email
- [ ] User can access quiz from URL provided in email
- [ ] User can take a quiz
- [ ] User can submit quiz responses
- [ ] User is presented with grade and results of quiz
- [ ] User can retrieve certificate (if passing) or is prompted to try again (if failing)

**Comment by A-L33** [comment]
@brentryanjohnson Ready for your review!

**Comment by brentryanjohnson** [comment]
@A-L33 ✅ Reviewed!

**Comment by A-L33** [comment]
@weiwang-gsa Good to go!

**Comment by weiwang-gsa** [comment]
@A-L33 When you get a chance, would you mind granting me access to the document? Thank you!

**Comment by A-L33** [comment]
Just gave you access!

**Comment by weiwang-gsa** [comment]
@melchoyce this issue is ready for design review just in case ( no design change involved in code though): https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/quiz/training_purchase_pc/

**Comment by melchoyce** [comment]
LGMT 👍

**Comment by JessicaMarine1** [comment]
@A-L33 this is ready for your review.

**Comment by A-L33** [comment]
Done!
