### ISSUE TITLE
Quiz | Fleet Card Training for A/OPCs

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#78]
As an A/OPC, I want to take the quiz for fleet card training so that I can comply with my regulatory requirements.

Pre-Condition:
- Quiz content is finalized
- Content is available [HERE](https://docs.google.com/document/d/1ljbP6YIv2H36R2FZ-Icmn2vixGfNR_QbVvPLSVG-zIc/edit#heading=h.gjdgxs)

Acceptance criteria:
- [ ] User can "register" for quiz using loginless approach
- [ ] User is sent email with unique URL (URL only active for 24 hours)
- [ ] User can access quiz from URL provided in email
- [ ] User can take a quiz
- [ ] User can submit quiz responses
- [ ] User is presented with grade and results of quiz
- [ ] User can retrieve certificate (if passing) or is prompted to try again (if failing)

**Comment by A-L33** [comment]
@brentryanjohnson Ready for your review!

**Comment by brentryanjohnson** [comment]
@A-L33 Reviewed! ✅

**Comment by weiwang-gsa** [comment]
@A-L33 @rebekahperillo this is ready for QA: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/

**Comment by A-L33** [comment]
Done!
