### ISSUE TITLE
Quiz | Travel Card Training for Account Holders/AOs

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#79]
As an Account Holders/AO, I want to take the quiz for travel card training so that I can comply with my regulatory requirements.

Pre-Condition:
- Quiz [content](https://docs.google.com/document/d/19RS0F0yeNvi3t4XDPegKikmQnBx_PotcJv9nRoI4cCM/edit#heading=h.gjdgxs) is finalized

Acceptance criteria:
- [ ] User can access quiz from URL provided in email
- [ ] User can take a quiz
- [ ] User can submit quiz responses

**Comment by JessicaMarine1** [comment]
@brentryanjohnson this content is ready for your review

**Comment by brentryanjohnson** [comment]
✅ Reviewed

**Comment by JessicaMarine1** [comment]
@jfredrickson5 here's the second quiz

**Comment by JessicaMarine1** [comment]
Logged issues in #101. Moving `Done`
