### ISSUE TITLE
Quiz | Purchase Card Training for Card/Account Holders & Approving Officials

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#80]
As an Account Holders/AO, I want to take the quiz for purchase card training so that I can comply with my regulatory requirements.

Pre-Condition:
- [Quiz content](https://docs.google.com/document/d/13aQzUDlyY-yLoE1lyTDvHnyFESMkNbjeNOH0sKiWPuw/edit#) is finalized

Acceptance criteria:
- [ ] User can "register" for quiz using loginless approach
- [ ] User is sent email
- [ ] User can access quiz from URL provided in email
- [ ] User can take a quiz
- [ ] User can submit quiz responses
- [ ] User is presented with grade and results of quiz
- [ ] User can retrieve certificate (if passing) or is prompted to try again (if failing)

**Comment by A-L33** [comment]
@brentryanjohnson Ready for your review!

**Comment by brentryanjohnson** [comment]
✅ @A-L33

**Comment by A-L33** [comment]
Content good to go.

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 @A-L33 This is ready for review: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/

**Comment by JessicaMarine1** [comment]
@A-L33 please review on both desktop AND mobile before moving to done.

**Comment by A-L33** [comment]
@weiwang-gsa I'm getting this error on mobile and desktop when I try and download the cert:
![image](https://user-images.githubusercontent.com/116583391/236577282-87a80625-1c3c-4e5a-b8f1-2b83c1b858dd.png)
Also, I am not able to access the cert from the certs page and the icon is missing:
![image](https://user-images.githubusercontent.com/116583391/236577822-c4c59692-1a96-444e-bc8b-e4d43a7c83d3.png)

**Comment by weiwang-gsa** [comment]
@A-L33 Added certificate piece, it is ready for QA review now: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/

**Comment by A-L33** [comment]
Done!
