### ISSUE TITLE
View Full Version of Training Material

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#88]
As a cardholder/AOPC/general user of the site, I want to be able to view/download/save a full training, so that I can view them outside of the system.

**Acceptance Criteria:**

- [ ] At the beginning of each training, a user can click a link to view a full version of the training materials in HTML without logging in
- [ ] Update first page of training as indicated [here](https://docs.google.com/document/d/13GupbzWON7SJOWdXHmvOxsdvnQohQXHIzuPJU61fdJk/edit#) | [design](https://www.figma.com/proto/bgNCEcglYMCDtEEBys04cx/SmartPay?node-id=643-10173&scaling=min-zoom&page-id=32%3A183&starting-point-node-id=294%3A9110)

Note: We decided **not** to pursue any PDF version or print-to-PDF prompt

**Comment by JessicaMarine1** [comment]
Q: The current training design has:

`View the training in HTML (508 compliant)`
`Download the training as a PDF`

Is the AC above sufficient to cover both or do we need to be more explicit?

**Comment by A-L33** [comment]
Let's assume 1 version in HTML.  Explore toggling print dialogue box and "print to PDF" function.

**Comment by JessicaMarine1** [comment]
@actuallyjenn can you please re-word the 2nd AC above to accurately reflect whatever design/wording changes are needed in the [grey box](https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/training_travel/). I feel like the lead-in sentence also needs tweaking.

**Comment by actuallyjenn** [comment]
@JessicaMarine1 just looking at this now. If we're only going to have the view link, it makes me wonder if we should remove the grey box and instead have the content all in one place? I made suggested edits in the [google doc](https://docs.google.com/document/d/13GupbzWON7SJOWdXHmvOxsdvnQohQXHIzuPJU61fdJk/edit#).

**Comment by A-L33** [comment]
@actuallyjenn @melchoyce I'm looking at the link without the gray box and I think in theory, it is ok.  What concerns me a bit is that the link is buried in the text and we rely on people reading through the text.  Thoughts here?  Are there any potential design things that can be done to highlight this function that doesn't need the box?

**Comment by actuallyjenn** [comment]
@A-L33, mel and i just met on this to discuss and we're not opposed to using the grey box to call out the text. we just came up with this option: https://www.figma.com/proto/bgNCEcglYMCDtEEBys04cx/SmartPay?node-id=643-10173&scaling=min-zoom&page-id=32%3A183&starting-point-node-id=294%3A9110, and i can update the google doc since we use that as the source of truth for content!

**Comment by JessicaMarine1** [comment]
@mark-meyer Please re-introduce the grey box ([design](https://www.figma.com/proto/bgNCEcglYMCDtEEBys04cx/SmartPay?node-id=643-10173&scaling=min-zoom&page-id=32%3A183&starting-point-node-id=294%3A9110)) and remove the `Skip ahead to quiz` link currently under the `Continue training` button

**Comment by A-L33** [comment]
Just noting the space after the links in the print.  But we can live with that.  Done!
