### ISSUE TITLE
Confirming Email Addresses

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#9]
As a system administrator, I want to ensure that emails from the training platform are delivered, so that I can confirm that users are using current and valid emails.

Acceptance criteria:
- As part of the registration process, users are prompted to enter in email addresses twice
- Users are not able to ""copy and paste"" email addresses on the second entry
- Users are not permitted to proceed with the registration process if the emails don't match
- Follow USWDS guidance for email validation

**Comment by mark-meyer** [comment]
Pasting this here for discussion. [USWDS guidance](https://designsystem.digital.gov/patterns/create-a-user-profile/email-address/) for email address inputs has:

>Do not require users to re-enter their email address, unless you have a good reason for doing so.

and

>Do allow users to paste their email address.

**Comment by jfredrickson5** [comment]
Regarding having an email confirmation field and disabling copy/paste: can we more closely examine the needs that drive these two criteria? I'm willing to bet that whatever problem is behind them could be solved in a more user-friendly way.

**Comment by johnbeallgsa** [comment]
The concern was that a user could make a mistake when typing their email address and copying/pasting it into the second box.  The incorrect email would match, and the user would never get the email with the link to take the training.  

Users would then contact the SmartPay team and say they have not received the email.  SmartPay would like to avoid getting those emails.

**Comment by actuallyjenn** [comment]
Considerations / questions from Jeff:
- Do you know the numbers on how often people enter their correct email address but they just don't have a registered account with that email, versus how many people enter the wrong email address with typos?
- Implement it with a single email field and see if help desk tickets don't get better, then revisit how to handle this

**Comment by JessicaMarine1** [comment]
After discussion, it was decided to **not** implement the dual email entry approach due to [USWDS guidance](https://designsystem.digital.gov/patterns/create-a-user-profile/email-address/) which federal agencies are required to follow by law.
